//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Google.Apis.Drive.v1.Data {
    
    
    /// <summary>The metadata for a file.</summary>
    public class File : Google.Apis.Requests.IDirectResponseSchema {
        
        private string _createdDate;
        
        private string _description;
        
        private string _downloadUrl;
        
        private string _etag;
        
        private string _fileExtension;
        
        private string _fileSize;
        
        private string _id;
        
        private File.IndexableTextData _indexableText;
        
        private string _kind;
        
        private File.LabelsData _labels;
        
        private string _lastViewedDate;
        
        private string _md5Checksum;
        
        private string _mimeType;
        
        private string _modifiedByMeDate;
        
        private string _modifiedDate;
        
        private System.Collections.Generic.IList<File.ParentsCollectionData> _parentsCollection;
        
        private string _selfLink;
        
        private string _title;
        
        private Permission _userPermission;
        
        /// <summary>Create time for this file (formatted ISO8601 timestamp).</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("createdDate")]
        public virtual string CreatedDate {
            get {
                return this._createdDate;
            }
            set {
                this._createdDate = value;
            }
        }
        
        /// <summary>A short description of the file</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("description")]
        public virtual string Description {
            get {
                return this._description;
            }
            set {
                this._description = value;
            }
        }
        
        /// <summary>Short term download URL for the file. This will only be populated on files with content stored in Drive.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("downloadUrl")]
        public virtual string DownloadUrl {
            get {
                return this._downloadUrl;
            }
            set {
                this._downloadUrl = value;
            }
        }
        
        /// <summary>ETag of the file.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("etag")]
        public virtual string ETag {
            get {
                return this._etag;
            }
            set {
                this._etag = value;
            }
        }
        
        /// <summary>The file extension used when downloading this file. This field is read only. To set the extension, include it on title when creating the file. This will only be populated on files with content stored in Drive.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("fileExtension")]
        public virtual string FileExtension {
            get {
                return this._fileExtension;
            }
            set {
                this._fileExtension = value;
            }
        }
        
        /// <summary>The size of the file in bytes. This will only be populated on files with content stored in Drive.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("fileSize")]
        public virtual string FileSize {
            get {
                return this._fileSize;
            }
            set {
                this._fileSize = value;
            }
        }
        
        /// <summary>The id of the file.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("id")]
        public virtual string Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        /// <summary>Indexable text attributes for the file (can only be written)</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("indexableText")]
        public virtual File.IndexableTextData IndexableText {
            get {
                return this._indexableText;
            }
            set {
                this._indexableText = value;
            }
        }
        
        /// <summary>The type of file. This is always drive#file</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this._kind;
            }
            set {
                this._kind = value;
            }
        }
        
        /// <summary>Labels for the file.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("labels")]
        public virtual File.LabelsData Labels {
            get {
                return this._labels;
            }
            set {
                this._labels = value;
            }
        }
        
        /// <summary>Last time this file was viewed by the user (formatted RFC 3339 timestamp).</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("lastViewedDate")]
        public virtual string LastViewedDate {
            get {
                return this._lastViewedDate;
            }
            set {
                this._lastViewedDate = value;
            }
        }
        
        /// <summary>An MD5 checksum for the content of this file. This will only be populated on files with content stored in Drive.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("md5Checksum")]
        public virtual string Md5Checksum {
            get {
                return this._md5Checksum;
            }
            set {
                this._md5Checksum = value;
            }
        }
        
        /// <summary>The mimetype of the file</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("mimeType")]
        public virtual string MimeType {
            get {
                return this._mimeType;
            }
            set {
                this._mimeType = value;
            }
        }
        
        /// <summary>Last time this file was modified by the user (formatted RFC 3339 timestamp).</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("modifiedByMeDate")]
        public virtual string ModifiedByMeDate {
            get {
                return this._modifiedByMeDate;
            }
            set {
                this._modifiedByMeDate = value;
            }
        }
        
        /// <summary>Last time this file was modified by anyone (formatted RFC 3339 timestamp).</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("modifiedDate")]
        public virtual string ModifiedDate {
            get {
                return this._modifiedDate;
            }
            set {
                this._modifiedDate = value;
            }
        }
        
        /// <summary>Collection of parent folders which contain this file.
        ///On insert, setting this field will put the file in all of the provided folders. If no folders are provided, the file will be placed in the default root folder. On update, this field is ignored.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("parentsCollection")]
        public virtual System.Collections.Generic.IList<File.ParentsCollectionData> ParentsCollection {
            get {
                return this._parentsCollection;
            }
            set {
                this._parentsCollection = value;
            }
        }
        
        /// <summary>A link back to this file.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("selfLink")]
        public virtual string SelfLink {
            get {
                return this._selfLink;
            }
            set {
                this._selfLink = value;
            }
        }
        
        /// <summary>The title of this file.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("title")]
        public virtual string Title {
            get {
                return this._title;
            }
            set {
                this._title = value;
            }
        }
        
        /// <summary>A single permission for a file.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("userPermission")]
        public virtual Permission UserPermission {
            get {
                return this._userPermission;
            }
            set {
                this._userPermission = value;
            }
        }
        
        /// <summary>Indexable text attributes for the file (can only be written)</summary>
        public class IndexableTextData {
            
            private string _text;
            
            /// <summary>The text to be indexed for this file</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("text")]
            public virtual string Text {
                get {
                    return this._text;
                }
                set {
                    this._text = value;
                }
            }
        }
        
        /// <summary>Labels for the file.</summary>
        public class LabelsData {
            
            private System.Nullable<bool> _hidden;
            
            private System.Nullable<bool> _starred;
            
            private System.Nullable<bool> _trashed;
            
            /// <summary>Whether this file is hidden from the user</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("hidden")]
            public virtual System.Nullable<bool> Hidden {
                get {
                    return this._hidden;
                }
                set {
                    this._hidden = value;
                }
            }
            
            /// <summary>Whether this file is starred by the user.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("starred")]
            public virtual System.Nullable<bool> Starred {
                get {
                    return this._starred;
                }
                set {
                    this._starred = value;
                }
            }
            
            /// <summary>Whether this file has been trashed.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("trashed")]
            public virtual System.Nullable<bool> Trashed {
                get {
                    return this._trashed;
                }
                set {
                    this._trashed = value;
                }
            }
        }
        
        public class ParentsCollectionData {
            
            private string _id;
            
            private string _parentLink;
            
            /// <summary>The id of this parent</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("id")]
            public virtual string Id {
                get {
                    return this._id;
                }
                set {
                    this._id = value;
                }
            }
            
            /// <summary>A link to get the metadata for this parent</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("parentLink")]
            public virtual string ParentLink {
                get {
                    return this._parentLink;
                }
                set {
                    this._parentLink = value;
                }
            }
        }
    }
    
    /// <summary>A single permission for a file.</summary>
    public class Permission {
        
        private System.Collections.Generic.IList<string> _additionalRoles;
        
        private string _etag;
        
        private string _kind;
        
        private string _role;
        
        private string _type;
        
        /// <summary>Any additional roles that this permission describes.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("additionalRoles")]
        public virtual System.Collections.Generic.IList<string> AdditionalRoles {
            get {
                return this._additionalRoles;
            }
            set {
                this._additionalRoles = value;
            }
        }
        
        /// <summary>An etag for this permission.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("etag")]
        public virtual string ETag {
            get {
                return this._etag;
            }
            set {
                this._etag = value;
            }
        }
        
        /// <summary>The kind of this permission. This is always drive#permission</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this._kind;
            }
            set {
                this._kind = value;
            }
        }
        
        /// <summary>The role that this permission describes. (For example: reader, writer, owner)</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("role")]
        public virtual string Role {
            get {
                return this._role;
            }
            set {
                this._role = value;
            }
        }
        
        /// <summary>The type of permission (For example: user, group etc).</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("type")]
        public virtual string Type {
            get {
                return this._type;
            }
            set {
                this._type = value;
            }
        }
    }
}
namespace Google.Apis.Drive.v1 {
    
    
    public partial class DriveService : Google.Apis.Services.BaseClientService {
        
        public const string Version = "v1";
        
        public static Google.Apis.Discovery.DiscoveryVersion DiscoveryVersionUsed = Google.Apis.Discovery.DiscoveryVersion.Version_1_0;
        
        private System.Collections.Generic.IDictionary<string, Google.Apis.Discovery.IParameter> _serviceParameters;
        
        public DriveService(Google.Apis.Services.BaseClientService.Initializer initializer) : 
                base(initializer) {
            this._files = new FilesResource(this, Authenticator);
            this.InitParameters();
        }
        
        public DriveService() : 
                this(new Google.Apis.Services.BaseClientService.Initializer()) {
        }
        
        public override System.Collections.Generic.IList<string> Features {
            get {
                return new string[0];
            }
        }
        
        public override string Name {
            get {
                return "drive";
            }
        }
        
        public override string BaseUri {
            get {
                return "https://www.googleapis.com/drive/v1/";
            }
        }
        
        public override string BasePath {
            get {
                return "/drive/v1/";
            }
        }
        
        public override System.Collections.Generic.IDictionary<string, Google.Apis.Discovery.IParameter> ServiceParameters {
            get {
                return this._serviceParameters;
            }
        }
        
        private void InitParameters() {
            System.Collections.Generic.Dictionary<string, Google.Apis.Discovery.IParameter> parameters = new System.Collections.Generic.Dictionary<string, Google.Apis.Discovery.IParameter>();
            parameters.Add("alt", Google.Apis.Util.Utilities.CreateRuntimeParameter("alt", false, "query", "json", null, new string[] {
                            "json"}));
            parameters.Add("fields", Google.Apis.Util.Utilities.CreateRuntimeParameter("fields", false, "query", null, null, new string[0]));
            parameters.Add("key", Google.Apis.Util.Utilities.CreateRuntimeParameter("key", false, "query", null, null, new string[0]));
            parameters.Add("oauth_token", Google.Apis.Util.Utilities.CreateRuntimeParameter("oauth_token", false, "query", null, null, new string[0]));
            parameters.Add("prettyPrint", Google.Apis.Util.Utilities.CreateRuntimeParameter("prettyPrint", false, "query", "true", null, new string[0]));
            parameters.Add("quotaUser", Google.Apis.Util.Utilities.CreateRuntimeParameter("quotaUser", false, "query", null, null, new string[0]));
            parameters.Add("userIp", Google.Apis.Util.Utilities.CreateRuntimeParameter("userIp", false, "query", null, null, new string[0]));
            this._serviceParameters = new Google.Apis.Util.ReadOnlyDictionary<string, Google.Apis.Discovery.IParameter>(parameters);
        }
        
        /// <summary>A list of all OAuth2.0 scopes. Each of these scopes relates to a permission or group of permissions that different methods of this API may need.</summary>
        public enum Scopes {
            
            /// <summary>View and manage Google Drive files that you have opened or created with this app</summary>
            [Google.Apis.Util.StringValueAttribute("https://www.googleapis.com/auth/drive.file")]
            DriveFile,
        }
    }
    
    public class FilesResource {
        
        private DriveService service;
        
        private Google.Apis.Authentication.IAuthenticator authenticator;
        
        private const string Resource = "files";
        
        public FilesResource(DriveService service, Google.Apis.Authentication.IAuthenticator authenticator) {
            this.service = service;
            this.authenticator = authenticator;
        }
        
        /// <summary>Gets a file&apos;s metadata by id.</summary>
        /// <param name="id">Required - The id for the file in question.</param>
        public virtual GetRequest Get(string id) {
            return new GetRequest(service, id);
        }
        
        /// <summary>Inserts a file, and any settable metadata or blob content sent with the request.</summary>
        public virtual InsertRequest Insert(Google.Apis.Drive.v1.Data.File body) {
            return new InsertRequest(service, body);
        }
        
        /// <summary>Inserts a file, and any settable metadata or blob content sent with the request.</summary>
        public virtual InsertMediaUpload Insert(Google.Apis.Drive.v1.Data.File body, System.IO.Stream stream, string contentType) {
            return new InsertMediaUpload(service, body, stream, contentType);
        }
        
        /// <summary>Updates file metadata and/or content. This method supports patch semantics.</summary>
        /// <param name="id">Required - The id for the file in question.</param>
        public virtual PatchRequest Patch(Google.Apis.Drive.v1.Data.File body, string id) {
            return new PatchRequest(service, body, id);
        }
        
        /// <summary>Updates file metadata and/or content</summary>
        /// <param name="id">Required - The id for the file in question.</param>
        public virtual UpdateRequest Update(Google.Apis.Drive.v1.Data.File body, string id) {
            return new UpdateRequest(service, body, id);
        }
        
        /// <summary>Updates file metadata and/or content</summary>
        /// <param name="id">Required - The id for the file in question.</param>
        public virtual UpdateMediaUpload Update(Google.Apis.Drive.v1.Data.File body, string id, System.IO.Stream stream, string contentType) {
            return new UpdateMediaUpload(service, body, id, stream, contentType);
        }
        
        /// <summary>This parameter is deprecated and has no function.</summary>
        public enum Projection {
            
            /// <summary>Deprecated</summary>
            [Google.Apis.Util.StringValueAttribute("BASIC")]
            BASIC,
            
            /// <summary>Deprecated</summary>
            [Google.Apis.Util.StringValueAttribute("FULL")]
            FULL,
        }
        
        public class GetRequest : Google.Apis.Requests.ClientServiceRequest<Google.Apis.Drive.v1.Data.File> {
            
            private string _alt;
            
            private string _fields;
            
            private string _oauth_token;
            
            private System.Nullable<bool> _prettyPrint;
            
            private string _quotaUser;
            
            private string _userIp;
            
            private string _id;
            
            private System.Nullable<Projection> _projection;
            
            private System.Nullable<bool> _updateViewedDate;
            
            public GetRequest(Google.Apis.Services.IClientService service, string id) : 
                    base(service) {
                this._id = id;
                this.InitParameters();
            }
            
            /// <summary>Data format for the response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("alt", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Alt {
                get {
                    return this._alt;
                }
                set {
                    this._alt = value;
                }
            }
            
            /// <summary>Selector specifying which fields to include in a partial response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("fields", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Fields {
                get {
                    return this._fields;
                }
                set {
                    this._fields = value;
                }
            }
            
            /// <summary>OAuth 2.0 token for the current user.</summary>
            [Google.Apis.Util.RequestParameterAttribute("oauth_token", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Oauth_token {
                get {
                    return this._oauth_token;
                }
                set {
                    this._oauth_token = value;
                }
            }
            
            /// <summary>Returns response with indentations and line breaks.</summary>
            [Google.Apis.Util.RequestParameterAttribute("prettyPrint", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> PrettyPrint {
                get {
                    return this._prettyPrint;
                }
                set {
                    this._prettyPrint = value;
                }
            }
            
            /// <summary>Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</summary>
            [Google.Apis.Util.RequestParameterAttribute("quotaUser", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string QuotaUser {
                get {
                    return this._quotaUser;
                }
                set {
                    this._quotaUser = value;
                }
            }
            
            /// <summary>IP address of the site where the request originates. Use this if you want to enforce per-user limits.</summary>
            [Google.Apis.Util.RequestParameterAttribute("userIp", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string UserIp {
                get {
                    return this._userIp;
                }
                set {
                    this._userIp = value;
                }
            }
            
            /// <summary>The id for the file in question.</summary>
            [Google.Apis.Util.RequestParameterAttribute("id", Google.Apis.Util.RequestParameterType.Path)]
            public virtual string Id {
                get {
                    return this._id;
                }
            }
            
            /// <summary>This parameter is deprecated and has no function.</summary>
            [Google.Apis.Util.RequestParameterAttribute("projection", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<Projection> Projection {
                get {
                    return this._projection;
                }
                set {
                    this._projection = value;
                }
            }
            
            /// <summary>Whether to update the view date after successfully retrieving the file.</summary>
            [Google.Apis.Util.RequestParameterAttribute("updateViewedDate", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> UpdateViewedDate {
                get {
                    return this._updateViewedDate;
                }
                set {
                    this._updateViewedDate = value;
                }
            }
            
            public override string MethodName {
                get {
                    return "get";
                }
            }
            
            public override string HttpMethod {
                get {
                    return "GET";
                }
            }
            
            public override string RestPath {
                get {
                    return "files/{id}";
                }
            }
            
            private void InitParameters() {
                System.Collections.Generic.Dictionary<string, Google.Apis.Discovery.IParameter> parameters = new System.Collections.Generic.Dictionary<string, Google.Apis.Discovery.IParameter>();
                parameters.Add("id", Google.Apis.Util.Utilities.CreateRuntimeParameter("id", true, "path", null, null, new string[0]));
                parameters.Add("projection", Google.Apis.Util.Utilities.CreateRuntimeParameter("projection", false, "query", null, null, new string[] {
                                "BASIC",
                                "FULL"}));
                parameters.Add("updateViewedDate", Google.Apis.Util.Utilities.CreateRuntimeParameter("updateViewedDate", false, "query", "true", null, new string[0]));
                this._requestParameters = new Google.Apis.Util.ReadOnlyDictionary<string, Google.Apis.Discovery.IParameter>(parameters);
            }
        }
        
        public class InsertRequest : Google.Apis.Requests.ClientServiceRequest<Google.Apis.Drive.v1.Data.File> {
            
            private string _alt;
            
            private string _fields;
            
            private string _oauth_token;
            
            private System.Nullable<bool> _prettyPrint;
            
            private string _quotaUser;
            
            private string _userIp;
            
            private Google.Apis.Drive.v1.Data.File _Body;
            
            public InsertRequest(Google.Apis.Services.IClientService service, Google.Apis.Drive.v1.Data.File body) : 
                    base(service) {
                this.Body = body;
                this.InitParameters();
            }
            
            /// <summary>Data format for the response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("alt", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Alt {
                get {
                    return this._alt;
                }
                set {
                    this._alt = value;
                }
            }
            
            /// <summary>Selector specifying which fields to include in a partial response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("fields", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Fields {
                get {
                    return this._fields;
                }
                set {
                    this._fields = value;
                }
            }
            
            /// <summary>OAuth 2.0 token for the current user.</summary>
            [Google.Apis.Util.RequestParameterAttribute("oauth_token", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Oauth_token {
                get {
                    return this._oauth_token;
                }
                set {
                    this._oauth_token = value;
                }
            }
            
            /// <summary>Returns response with indentations and line breaks.</summary>
            [Google.Apis.Util.RequestParameterAttribute("prettyPrint", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> PrettyPrint {
                get {
                    return this._prettyPrint;
                }
                set {
                    this._prettyPrint = value;
                }
            }
            
            /// <summary>Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</summary>
            [Google.Apis.Util.RequestParameterAttribute("quotaUser", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string QuotaUser {
                get {
                    return this._quotaUser;
                }
                set {
                    this._quotaUser = value;
                }
            }
            
            /// <summary>IP address of the site where the request originates. Use this if you want to enforce per-user limits.</summary>
            [Google.Apis.Util.RequestParameterAttribute("userIp", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string UserIp {
                get {
                    return this._userIp;
                }
                set {
                    this._userIp = value;
                }
            }
            
            /// <summary>Gets/Sets the Body of this Request.</summary>
            public virtual Google.Apis.Drive.v1.Data.File Body {
                get {
                    return this._Body;
                }
                set {
                    this._Body = value;
                }
            }
            
            public override string MethodName {
                get {
                    return "insert";
                }
            }
            
            public override string HttpMethod {
                get {
                    return "POST";
                }
            }
            
            public override string RestPath {
                get {
                    return "files";
                }
            }
            
            protected override object GetBody() {
                return this.Body;
            }
            
            private void InitParameters() {
                System.Collections.Generic.Dictionary<string, Google.Apis.Discovery.IParameter> parameters = new System.Collections.Generic.Dictionary<string, Google.Apis.Discovery.IParameter>();
                this._requestParameters = new Google.Apis.Util.ReadOnlyDictionary<string, Google.Apis.Discovery.IParameter>(parameters);
            }
        }
        
        public class InsertMediaUpload : Google.Apis.Upload.ResumableUpload<Google.Apis.Drive.v1.Data.File, Google.Apis.Drive.v1.Data.File> {
            
            private string _alt;
            
            private string _fields;
            
            private string _oauth_token;
            
            private System.Nullable<bool> _prettyPrint;
            
            private string _quotaUser;
            
            private string _userIp;
            
            public InsertMediaUpload(Google.Apis.Services.IClientService service, Google.Apis.Drive.v1.Data.File body, System.IO.Stream stream, string contentType) : 
                    base(service, string.Format("/{0}{1}{2}", "upload", service.BasePath, "files"), "POST", stream, contentType) {
                this.Body = body;
            }
            
            /// <summary>Data format for the response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("alt", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Alt {
                get {
                    return this._alt;
                }
                set {
                    this._alt = value;
                }
            }
            
            /// <summary>Selector specifying which fields to include in a partial response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("fields", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Fields {
                get {
                    return this._fields;
                }
                set {
                    this._fields = value;
                }
            }
            
            /// <summary>OAuth 2.0 token for the current user.</summary>
            [Google.Apis.Util.RequestParameterAttribute("oauth_token", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Oauth_token {
                get {
                    return this._oauth_token;
                }
                set {
                    this._oauth_token = value;
                }
            }
            
            /// <summary>Returns response with indentations and line breaks.</summary>
            [Google.Apis.Util.RequestParameterAttribute("prettyPrint", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> PrettyPrint {
                get {
                    return this._prettyPrint;
                }
                set {
                    this._prettyPrint = value;
                }
            }
            
            /// <summary>Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</summary>
            [Google.Apis.Util.RequestParameterAttribute("quotaUser", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string QuotaUser {
                get {
                    return this._quotaUser;
                }
                set {
                    this._quotaUser = value;
                }
            }
            
            /// <summary>IP address of the site where the request originates. Use this if you want to enforce per-user limits.</summary>
            [Google.Apis.Util.RequestParameterAttribute("userIp", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string UserIp {
                get {
                    return this._userIp;
                }
                set {
                    this._userIp = value;
                }
            }
        }
        
        public class PatchRequest : Google.Apis.Requests.ClientServiceRequest<Google.Apis.Drive.v1.Data.File> {
            
            private string _alt;
            
            private string _fields;
            
            private string _oauth_token;
            
            private System.Nullable<bool> _prettyPrint;
            
            private string _quotaUser;
            
            private string _userIp;
            
            private string _id;
            
            private System.Nullable<bool> _newRevision;
            
            private System.Nullable<bool> _updateModifiedDate;
            
            private System.Nullable<bool> _updateViewedDate;
            
            private Google.Apis.Drive.v1.Data.File _Body;
            
            public PatchRequest(Google.Apis.Services.IClientService service, Google.Apis.Drive.v1.Data.File body, string id) : 
                    base(service) {
                this.Body = body;
                this._id = id;
                this.InitParameters();
            }
            
            /// <summary>Data format for the response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("alt", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Alt {
                get {
                    return this._alt;
                }
                set {
                    this._alt = value;
                }
            }
            
            /// <summary>Selector specifying which fields to include in a partial response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("fields", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Fields {
                get {
                    return this._fields;
                }
                set {
                    this._fields = value;
                }
            }
            
            /// <summary>OAuth 2.0 token for the current user.</summary>
            [Google.Apis.Util.RequestParameterAttribute("oauth_token", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Oauth_token {
                get {
                    return this._oauth_token;
                }
                set {
                    this._oauth_token = value;
                }
            }
            
            /// <summary>Returns response with indentations and line breaks.</summary>
            [Google.Apis.Util.RequestParameterAttribute("prettyPrint", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> PrettyPrint {
                get {
                    return this._prettyPrint;
                }
                set {
                    this._prettyPrint = value;
                }
            }
            
            /// <summary>Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</summary>
            [Google.Apis.Util.RequestParameterAttribute("quotaUser", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string QuotaUser {
                get {
                    return this._quotaUser;
                }
                set {
                    this._quotaUser = value;
                }
            }
            
            /// <summary>IP address of the site where the request originates. Use this if you want to enforce per-user limits.</summary>
            [Google.Apis.Util.RequestParameterAttribute("userIp", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string UserIp {
                get {
                    return this._userIp;
                }
                set {
                    this._userIp = value;
                }
            }
            
            /// <summary>The id for the file in question.</summary>
            [Google.Apis.Util.RequestParameterAttribute("id", Google.Apis.Util.RequestParameterType.Path)]
            public virtual string Id {
                get {
                    return this._id;
                }
            }
            
            /// <summary>Whether a blob upload should create a new revision. If not set or false, the blob data in the current head revision will be replaced.</summary>
            [Google.Apis.Util.RequestParameterAttribute("newRevision", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> NewRevision {
                get {
                    return this._newRevision;
                }
                set {
                    this._newRevision = value;
                }
            }
            
            /// <summary>Controls updating the modified date of the file. If true, the modified date will be updated to the current time, regardless of whether other changes are being made. If false, the modified date will only be updated to the current time if other changes are also being made (changing the title, for example).</summary>
            [Google.Apis.Util.RequestParameterAttribute("updateModifiedDate", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> UpdateModifiedDate {
                get {
                    return this._updateModifiedDate;
                }
                set {
                    this._updateModifiedDate = value;
                }
            }
            
            /// <summary>Whether to update the view date after successfully updating the file.</summary>
            [Google.Apis.Util.RequestParameterAttribute("updateViewedDate", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> UpdateViewedDate {
                get {
                    return this._updateViewedDate;
                }
                set {
                    this._updateViewedDate = value;
                }
            }
            
            /// <summary>Gets/Sets the Body of this Request.</summary>
            public virtual Google.Apis.Drive.v1.Data.File Body {
                get {
                    return this._Body;
                }
                set {
                    this._Body = value;
                }
            }
            
            public override string MethodName {
                get {
                    return "patch";
                }
            }
            
            public override string HttpMethod {
                get {
                    return "PATCH";
                }
            }
            
            public override string RestPath {
                get {
                    return "files/{id}";
                }
            }
            
            protected override object GetBody() {
                return this.Body;
            }
            
            private void InitParameters() {
                System.Collections.Generic.Dictionary<string, Google.Apis.Discovery.IParameter> parameters = new System.Collections.Generic.Dictionary<string, Google.Apis.Discovery.IParameter>();
                parameters.Add("id", Google.Apis.Util.Utilities.CreateRuntimeParameter("id", true, "path", null, null, new string[0]));
                parameters.Add("newRevision", Google.Apis.Util.Utilities.CreateRuntimeParameter("newRevision", false, "query", "true", null, new string[0]));
                parameters.Add("updateModifiedDate", Google.Apis.Util.Utilities.CreateRuntimeParameter("updateModifiedDate", false, "query", "false", null, new string[0]));
                parameters.Add("updateViewedDate", Google.Apis.Util.Utilities.CreateRuntimeParameter("updateViewedDate", false, "query", "true", null, new string[0]));
                this._requestParameters = new Google.Apis.Util.ReadOnlyDictionary<string, Google.Apis.Discovery.IParameter>(parameters);
            }
        }
        
        public class UpdateRequest : Google.Apis.Requests.ClientServiceRequest<Google.Apis.Drive.v1.Data.File> {
            
            private string _alt;
            
            private string _fields;
            
            private string _oauth_token;
            
            private System.Nullable<bool> _prettyPrint;
            
            private string _quotaUser;
            
            private string _userIp;
            
            private string _id;
            
            private System.Nullable<bool> _newRevision;
            
            private System.Nullable<bool> _updateModifiedDate;
            
            private System.Nullable<bool> _updateViewedDate;
            
            private Google.Apis.Drive.v1.Data.File _Body;
            
            public UpdateRequest(Google.Apis.Services.IClientService service, Google.Apis.Drive.v1.Data.File body, string id) : 
                    base(service) {
                this.Body = body;
                this._id = id;
                this.InitParameters();
            }
            
            /// <summary>Data format for the response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("alt", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Alt {
                get {
                    return this._alt;
                }
                set {
                    this._alt = value;
                }
            }
            
            /// <summary>Selector specifying which fields to include in a partial response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("fields", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Fields {
                get {
                    return this._fields;
                }
                set {
                    this._fields = value;
                }
            }
            
            /// <summary>OAuth 2.0 token for the current user.</summary>
            [Google.Apis.Util.RequestParameterAttribute("oauth_token", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Oauth_token {
                get {
                    return this._oauth_token;
                }
                set {
                    this._oauth_token = value;
                }
            }
            
            /// <summary>Returns response with indentations and line breaks.</summary>
            [Google.Apis.Util.RequestParameterAttribute("prettyPrint", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> PrettyPrint {
                get {
                    return this._prettyPrint;
                }
                set {
                    this._prettyPrint = value;
                }
            }
            
            /// <summary>Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</summary>
            [Google.Apis.Util.RequestParameterAttribute("quotaUser", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string QuotaUser {
                get {
                    return this._quotaUser;
                }
                set {
                    this._quotaUser = value;
                }
            }
            
            /// <summary>IP address of the site where the request originates. Use this if you want to enforce per-user limits.</summary>
            [Google.Apis.Util.RequestParameterAttribute("userIp", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string UserIp {
                get {
                    return this._userIp;
                }
                set {
                    this._userIp = value;
                }
            }
            
            /// <summary>The id for the file in question.</summary>
            [Google.Apis.Util.RequestParameterAttribute("id", Google.Apis.Util.RequestParameterType.Path)]
            public virtual string Id {
                get {
                    return this._id;
                }
            }
            
            /// <summary>Whether a blob upload should create a new revision. If not set or false, the blob data in the current head revision will be replaced.</summary>
            [Google.Apis.Util.RequestParameterAttribute("newRevision", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> NewRevision {
                get {
                    return this._newRevision;
                }
                set {
                    this._newRevision = value;
                }
            }
            
            /// <summary>Controls updating the modified date of the file. If true, the modified date will be updated to the current time, regardless of whether other changes are being made. If false, the modified date will only be updated to the current time if other changes are also being made (changing the title, for example).</summary>
            [Google.Apis.Util.RequestParameterAttribute("updateModifiedDate", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> UpdateModifiedDate {
                get {
                    return this._updateModifiedDate;
                }
                set {
                    this._updateModifiedDate = value;
                }
            }
            
            /// <summary>Whether to update the view date after successfully updating the file.</summary>
            [Google.Apis.Util.RequestParameterAttribute("updateViewedDate", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> UpdateViewedDate {
                get {
                    return this._updateViewedDate;
                }
                set {
                    this._updateViewedDate = value;
                }
            }
            
            /// <summary>Gets/Sets the Body of this Request.</summary>
            public virtual Google.Apis.Drive.v1.Data.File Body {
                get {
                    return this._Body;
                }
                set {
                    this._Body = value;
                }
            }
            
            public override string MethodName {
                get {
                    return "update";
                }
            }
            
            public override string HttpMethod {
                get {
                    return "PUT";
                }
            }
            
            public override string RestPath {
                get {
                    return "files/{id}";
                }
            }
            
            protected override object GetBody() {
                return this.Body;
            }
            
            private void InitParameters() {
                System.Collections.Generic.Dictionary<string, Google.Apis.Discovery.IParameter> parameters = new System.Collections.Generic.Dictionary<string, Google.Apis.Discovery.IParameter>();
                parameters.Add("id", Google.Apis.Util.Utilities.CreateRuntimeParameter("id", true, "path", null, null, new string[0]));
                parameters.Add("newRevision", Google.Apis.Util.Utilities.CreateRuntimeParameter("newRevision", false, "query", "true", null, new string[0]));
                parameters.Add("updateModifiedDate", Google.Apis.Util.Utilities.CreateRuntimeParameter("updateModifiedDate", false, "query", "false", null, new string[0]));
                parameters.Add("updateViewedDate", Google.Apis.Util.Utilities.CreateRuntimeParameter("updateViewedDate", false, "query", "true", null, new string[0]));
                this._requestParameters = new Google.Apis.Util.ReadOnlyDictionary<string, Google.Apis.Discovery.IParameter>(parameters);
            }
        }
        
        public class UpdateMediaUpload : Google.Apis.Upload.ResumableUpload<Google.Apis.Drive.v1.Data.File, Google.Apis.Drive.v1.Data.File> {
            
            private string _alt;
            
            private string _fields;
            
            private string _oauth_token;
            
            private System.Nullable<bool> _prettyPrint;
            
            private string _quotaUser;
            
            private string _userIp;
            
            private string _id;
            
            private System.Nullable<bool> _newRevision;
            
            private System.Nullable<bool> _updateModifiedDate;
            
            private System.Nullable<bool> _updateViewedDate;
            
            public UpdateMediaUpload(Google.Apis.Services.IClientService service, Google.Apis.Drive.v1.Data.File body, string id, System.IO.Stream stream, string contentType) : 
                    base(service, string.Format("/{0}{1}{2}", "upload", service.BasePath, "files/{id}"), "PUT", stream, contentType) {
                this.Body = body;
                this._id = id;
            }
            
            /// <summary>Data format for the response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("alt", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Alt {
                get {
                    return this._alt;
                }
                set {
                    this._alt = value;
                }
            }
            
            /// <summary>Selector specifying which fields to include in a partial response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("fields", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Fields {
                get {
                    return this._fields;
                }
                set {
                    this._fields = value;
                }
            }
            
            /// <summary>OAuth 2.0 token for the current user.</summary>
            [Google.Apis.Util.RequestParameterAttribute("oauth_token", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Oauth_token {
                get {
                    return this._oauth_token;
                }
                set {
                    this._oauth_token = value;
                }
            }
            
            /// <summary>Returns response with indentations and line breaks.</summary>
            [Google.Apis.Util.RequestParameterAttribute("prettyPrint", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> PrettyPrint {
                get {
                    return this._prettyPrint;
                }
                set {
                    this._prettyPrint = value;
                }
            }
            
            /// <summary>Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</summary>
            [Google.Apis.Util.RequestParameterAttribute("quotaUser", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string QuotaUser {
                get {
                    return this._quotaUser;
                }
                set {
                    this._quotaUser = value;
                }
            }
            
            /// <summary>IP address of the site where the request originates. Use this if you want to enforce per-user limits.</summary>
            [Google.Apis.Util.RequestParameterAttribute("userIp", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string UserIp {
                get {
                    return this._userIp;
                }
                set {
                    this._userIp = value;
                }
            }
            
            /// <summary>The id for the file in question.</summary>
            [Google.Apis.Util.RequestParameterAttribute("id", Google.Apis.Util.RequestParameterType.Path)]
            public virtual string Id {
                get {
                    return this._id;
                }
            }
            
            /// <summary>Whether a blob upload should create a new revision. If not set or false, the blob data in the current head revision will be replaced.</summary>
            [Google.Apis.Util.RequestParameterAttribute("newRevision", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> NewRevision {
                get {
                    return this._newRevision;
                }
                set {
                    this._newRevision = value;
                }
            }
            
            /// <summary>Controls updating the modified date of the file. If true, the modified date will be updated to the current time, regardless of whether other changes are being made. If false, the modified date will only be updated to the current time if other changes are also being made (changing the title, for example).</summary>
            [Google.Apis.Util.RequestParameterAttribute("updateModifiedDate", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> UpdateModifiedDate {
                get {
                    return this._updateModifiedDate;
                }
                set {
                    this._updateModifiedDate = value;
                }
            }
            
            /// <summary>Whether to update the view date after successfully updating the file.</summary>
            [Google.Apis.Util.RequestParameterAttribute("updateViewedDate", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> UpdateViewedDate {
                get {
                    return this._updateViewedDate;
                }
                set {
                    this._updateViewedDate = value;
                }
            }
        }
    }
    
    public partial class DriveService {
        
        private const string Resource = "";
        
        private FilesResource _files;
        
        private Google.Apis.Services.IClientService service {
            get {
                return this;
            }
        }
        
        public virtual FilesResource Files {
            get {
                return this._files;
            }
        }
    }
}
