//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Google.Apis.Adsense.v1.Data {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    
    
    public class AdClient {
        
        private string id;
        
        private string kind;
        
        private string productCode;
        
        private System.Nullable<bool> supportsReporting;
        
        /// <summary>Unique identifier of this ad client.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("id")]
        public virtual string Id {
            get {
                return this.id;
            }
            set {
                this.id = value;
            }
        }
        
        /// <summary>Kind of resource this is, in this case adsense#adClient.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this.kind;
            }
            set {
                this.kind = value;
            }
        }
        
        /// <summary>This ad client&apos;s product code, which corresponds to the PRODUCT_CODE report dimension.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("productCode")]
        public virtual string ProductCode {
            get {
                return this.productCode;
            }
            set {
                this.productCode = value;
            }
        }
        
        /// <summary>Whether this ad client supports being reported on.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("supportsReporting")]
        public virtual System.Nullable<bool> SupportsReporting {
            get {
                return this.supportsReporting;
            }
            set {
                this.supportsReporting = value;
            }
        }
    }
    
    public class AdClients : Google.Apis.Requests.IDirectResponseSchema {
        
        private string etag;
        
        private IList<AdClient> items;
        
        private string kind;
        
        private string nextPageToken;
        
        private Google.Apis.Requests.RequestError error;
        
        /// <summary>ETag of this response for caching purposes.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("etag")]
        public virtual string ETag {
            get {
                return this.etag;
            }
            set {
                this.etag = value;
            }
        }
        
        /// <summary>The ad clients returned in this list response.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("items")]
        public virtual IList<AdClient> Items {
            get {
                return this.items;
            }
            set {
                this.items = value;
            }
        }
        
        /// <summary>Kind of list this is, in this case adsense#adClients.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this.kind;
            }
            set {
                this.kind = value;
            }
        }
        
        /// <summary>Continuation token used to page through ad clients. To retrieve the next page of results, set the next request&apos;s &quot;pageToken&quot; value to this.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("nextPageToken")]
        public virtual string NextPageToken {
            get {
                return this.nextPageToken;
            }
            set {
                this.nextPageToken = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("error")]
        public virtual Google.Apis.Requests.RequestError Error {
            get {
                return this.error;
            }
            set {
                this.error = value;
            }
        }
    }
    
    public class AdUnit {
        
        private string code;
        
        private string id;
        
        private string kind;
        
        private string name;
        
        private string status;
        
        /// <summary>Identity code of this ad unit, not necessarily unique across ad clients.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("code")]
        public virtual string Code {
            get {
                return this.code;
            }
            set {
                this.code = value;
            }
        }
        
        /// <summary>Unique identifier of this ad unit. This should be considered an opaque identifier; it is not safe to rely on it being in any particular format.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("id")]
        public virtual string Id {
            get {
                return this.id;
            }
            set {
                this.id = value;
            }
        }
        
        /// <summary>Kind of resource this is, in this case adsense#adUnit.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this.kind;
            }
            set {
                this.kind = value;
            }
        }
        
        /// <summary>Name of this ad unit.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("name")]
        public virtual string Name {
            get {
                return this.name;
            }
            set {
                this.name = value;
            }
        }
        
        /// <summary>Status of this ad unit. Possible values are:
        ///NEW: Indicates that the ad unit was created within the last seven days and does not yet have any activity associated with it.
        ///
        ///ACTIVE: Indicates that there has been activity on this ad unit in the last seven days.
        ///
        ///INACTIVE: Indicates that there has been no activity on this ad unit in the last seven days.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("status")]
        public virtual string Status {
            get {
                return this.status;
            }
            set {
                this.status = value;
            }
        }
    }
    
    public class AdUnits : Google.Apis.Requests.IDirectResponseSchema {
        
        private string etag;
        
        private IList<AdUnit> items;
        
        private string kind;
        
        private string nextPageToken;
        
        private Google.Apis.Requests.RequestError error;
        
        /// <summary>ETag of this response for caching purposes.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("etag")]
        public virtual string ETag {
            get {
                return this.etag;
            }
            set {
                this.etag = value;
            }
        }
        
        /// <summary>The ad units returned in this list response.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("items")]
        public virtual IList<AdUnit> Items {
            get {
                return this.items;
            }
            set {
                this.items = value;
            }
        }
        
        /// <summary>Kind of list this is, in this case adsense#adUnits.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this.kind;
            }
            set {
                this.kind = value;
            }
        }
        
        /// <summary>Continuation token used to page through ad units. To retrieve the next page of results, set the next request&apos;s &quot;pageToken&quot; value to this.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("nextPageToken")]
        public virtual string NextPageToken {
            get {
                return this.nextPageToken;
            }
            set {
                this.nextPageToken = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("error")]
        public virtual Google.Apis.Requests.RequestError Error {
            get {
                return this.error;
            }
            set {
                this.error = value;
            }
        }
    }
    
    public class AdsenseReportsGenerateResponse : Google.Apis.Requests.IDirectResponseSchema {
        
        private IList<System.String> averages;
        
        private IList<AdsenseReportsGenerateResponse.HeadersData> headers;
        
        private string kind;
        
        private IList<IList<System.String>> rows;
        
        private string totalMatchedRows;
        
        private IList<System.String> totals;
        
        private IList<System.String> warnings;
        
        private Google.Apis.Requests.RequestError error;
        
        private string eTag;
        
        /// <summary>The averages of the report. This is the same length as any other row in the report; cells corresponding to dimension columns are empty.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("averages")]
        public virtual IList<System.String> Averages {
            get {
                return this.averages;
            }
            set {
                this.averages = value;
            }
        }
        
        /// <summary>The header information of the columns requested in the report. This is a list of headers; one for each dimension in the request, followed by one for each metric in the request.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("headers")]
        public virtual IList<AdsenseReportsGenerateResponse.HeadersData> Headers {
            get {
                return this.headers;
            }
            set {
                this.headers = value;
            }
        }
        
        /// <summary>Kind this is, in this case adsense#report.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this.kind;
            }
            set {
                this.kind = value;
            }
        }
        
        /// <summary>The output rows of the report. Each row is a list of cells; one for each dimension in the request, followed by one for each metric in the request. The dimension cells contain strings, and the metric cells contain numbers.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("rows")]
        public virtual IList<IList<System.String>> Rows {
            get {
                return this.rows;
            }
            set {
                this.rows = value;
            }
        }
        
        /// <summary>The total number of rows matched by the report request. Fewer rows may be returned in the response due to being limited by the row count requested or the report row limit.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("totalMatchedRows")]
        public virtual string TotalMatchedRows {
            get {
                return this.totalMatchedRows;
            }
            set {
                this.totalMatchedRows = value;
            }
        }
        
        /// <summary>The totals of the report. This is the same length as any other row in the report; cells corresponding to dimension columns are empty.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("totals")]
        public virtual IList<System.String> Totals {
            get {
                return this.totals;
            }
            set {
                this.totals = value;
            }
        }
        
        /// <summary>Any warnings associated with generation of the report.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("warnings")]
        public virtual IList<System.String> Warnings {
            get {
                return this.warnings;
            }
            set {
                this.warnings = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("error")]
        public virtual Google.Apis.Requests.RequestError Error {
            get {
                return this.error;
            }
            set {
                this.error = value;
            }
        }
        
        public virtual string ETag {
            get {
                return this.eTag;
            }
            set {
                this.eTag = value;
            }
        }
        
        public class HeadersData {
            
            private string currency;
            
            private string name;
            
            private string type;
            
            /// <summary>The currency of this column. Only present if the header type is METRIC_CURRENCY.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("currency")]
            public virtual string Currency {
                get {
                    return this.currency;
                }
                set {
                    this.currency = value;
                }
            }
            
            /// <summary>The name of the header.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("name")]
            public virtual string Name {
                get {
                    return this.name;
                }
                set {
                    this.name = value;
                }
            }
            
            /// <summary>The type of the header; one of DIMENSION, METRIC_TALLY, METRIC_RATIO, or METRIC_CURRENCY.</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("type")]
            public virtual string Type {
                get {
                    return this.type;
                }
                set {
                    this.type = value;
                }
            }
        }
    }
    
    public class CustomChannel {
        
        private string code;
        
        private string id;
        
        private string kind;
        
        private string name;
        
        /// <summary>Code of this custom channel, not necessarily unique across ad clients.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("code")]
        public virtual string Code {
            get {
                return this.code;
            }
            set {
                this.code = value;
            }
        }
        
        /// <summary>Unique identifier of this custom channel. This should be considered an opaque identifier; it is not safe to rely on it being in any particular format.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("id")]
        public virtual string Id {
            get {
                return this.id;
            }
            set {
                this.id = value;
            }
        }
        
        /// <summary>Kind of resource this is, in this case adsense#customChannel.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this.kind;
            }
            set {
                this.kind = value;
            }
        }
        
        /// <summary>Name of this custom channel.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("name")]
        public virtual string Name {
            get {
                return this.name;
            }
            set {
                this.name = value;
            }
        }
    }
    
    public class CustomChannels : Google.Apis.Requests.IDirectResponseSchema {
        
        private string etag;
        
        private IList<CustomChannel> items;
        
        private string kind;
        
        private string nextPageToken;
        
        private Google.Apis.Requests.RequestError error;
        
        /// <summary>ETag of this response for caching purposes.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("etag")]
        public virtual string ETag {
            get {
                return this.etag;
            }
            set {
                this.etag = value;
            }
        }
        
        /// <summary>The custom channels returned in this list response.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("items")]
        public virtual IList<CustomChannel> Items {
            get {
                return this.items;
            }
            set {
                this.items = value;
            }
        }
        
        /// <summary>Kind of list this is, in this case adsense#customChannels.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this.kind;
            }
            set {
                this.kind = value;
            }
        }
        
        /// <summary>Continuation token used to page through custom channels. To retrieve the next page of results, set the next request&apos;s &quot;pageToken&quot; value to this.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("nextPageToken")]
        public virtual string NextPageToken {
            get {
                return this.nextPageToken;
            }
            set {
                this.nextPageToken = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("error")]
        public virtual Google.Apis.Requests.RequestError Error {
            get {
                return this.error;
            }
            set {
                this.error = value;
            }
        }
    }
    
    public class UrlChannel {
        
        private string id;
        
        private string kind;
        
        private string urlPattern;
        
        /// <summary>Unique identifier of this URL channel. This should be considered an opaque identifier; it is not safe to rely on it being in any particular format.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("id")]
        public virtual string Id {
            get {
                return this.id;
            }
            set {
                this.id = value;
            }
        }
        
        /// <summary>Kind of resource this is, in this case adsense#urlChannel.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this.kind;
            }
            set {
                this.kind = value;
            }
        }
        
        /// <summary>URL Pattern of this URL channel. Does not include &quot;http://&quot; or &quot;https://&quot;. Example: www.example.com/home</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("urlPattern")]
        public virtual string UrlPattern {
            get {
                return this.urlPattern;
            }
            set {
                this.urlPattern = value;
            }
        }
    }
    
    public class UrlChannels : Google.Apis.Requests.IDirectResponseSchema {
        
        private string etag;
        
        private IList<UrlChannel> items;
        
        private string kind;
        
        private string nextPageToken;
        
        private Google.Apis.Requests.RequestError error;
        
        /// <summary>ETag of this response for caching purposes.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("etag")]
        public virtual string ETag {
            get {
                return this.etag;
            }
            set {
                this.etag = value;
            }
        }
        
        /// <summary>The URL channels returned in this list response.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("items")]
        public virtual IList<UrlChannel> Items {
            get {
                return this.items;
            }
            set {
                this.items = value;
            }
        }
        
        /// <summary>Kind of list this is, in this case adsense#urlChannels.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this.kind;
            }
            set {
                this.kind = value;
            }
        }
        
        /// <summary>Continuation token used to page through URL channels. To retrieve the next page of results, set the next request&apos;s &quot;pageToken&quot; value to this.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("nextPageToken")]
        public virtual string NextPageToken {
            get {
                return this.nextPageToken;
            }
            set {
                this.nextPageToken = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("error")]
        public virtual Google.Apis.Requests.RequestError Error {
            get {
                return this.error;
            }
            set {
                this.error = value;
            }
        }
    }
}
namespace Google.Apis.Adsense.v1 {
    using System;
    using System.IO;
    using System.Collections.Generic;
    using Google.Apis;
    using Google.Apis.Discovery;
    
    
    public partial class AdsenseService : Google.Apis.Discovery.IRequestProvider {
        
        private Google.Apis.Discovery.IService genericService;
        
        private Google.Apis.Authentication.IAuthenticator authenticator;
        
        private const string DiscoveryDocument = "{\"kind\":\"discovery#restDescription\",\"id\":\"adsense:v1\",\"name\":\"adsense\",\"version\":" +
            "\"v1\",\"title\":\"AdSense Management API\",\"description\":\"Gives AdSense publishers ac" +
            "cess to their inventory and the ability to generate reports\",\"icons\":{\"x16\":\"htt" +
            "p://www.google.com/images/icons/product/adsense-16.png\",\"x32\":\"http://www.google" +
            ".com/images/icons/product/adsense-32.png\"},\"documentationLink\":\"https://code.goo" +
            "gle.com/apis/adsense/management/\",\"labels\":[\"labs\"],\"protocol\":\"rest\",\"basePath\"" +
            ":\"/adsense/v1/\",\"parameters\":{\"alt\":{\"type\":\"string\",\"description\":\"Data format " +
            "for the response.\",\"default\":\"json\",\"enum\":[\"json\"],\"enumDescriptions\":[\"Respons" +
            "es with Content-Type of application/json\"],\"location\":\"query\"},\"fields\":{\"type\":" +
            "\"string\",\"description\":\"Selector specifying which fields to include in a partial" +
            " response.\",\"location\":\"query\"},\"key\":{\"type\":\"string\",\"description\":\"API key. Y" +
            "our API key identifies your project and provides you with API access, quota, and" +
            " reports. Required unless you provide an OAuth 2.0 token.\",\"location\":\"query\"},\"" +
            "oauth_token\":{\"type\":\"string\",\"description\":\"OAuth 2.0 token for the current use" +
            "r.\",\"location\":\"query\"},\"prettyPrint\":{\"type\":\"boolean\",\"description\":\"Returns r" +
            "esponse with indentations and line breaks.\",\"default\":\"true\",\"location\":\"query\"}" +
            ",\"quotaUser\":{\"type\":\"string\",\"description\":\"Available to use for quota purposes" +
            " for server-side applications. Can be any arbitrary string assigned to a user, b" +
            "ut should not exceed 40 characters. Overrides userIp if both are provided.\",\"loc" +
            "ation\":\"query\"},\"userIp\":{\"type\":\"string\",\"description\":\"IP address of the site " +
            "where the request originates. Use this if you want to enforce per-user limits.\"," +
            "\"location\":\"query\"}},\"auth\":{\"oauth2\":{\"scopes\":{\"https://www.googleapis.com/aut" +
            "h/adsense\":{\"description\":\"View and manage your AdSense data\"},\"https://www.goog" +
            "leapis.com/auth/adsense.readonly\":{\"description\":\"View your AdSense data\"}}}},\"s" +
            "chemas\":{\"AdClient\":{\"id\":\"AdClient\",\"type\":\"object\",\"properties\":{\"id\":{\"type\":" +
            "\"string\",\"description\":\"Unique identifier of this ad client.\"},\"kind\":{\"type\":\"s" +
            "tring\",\"description\":\"Kind of resource this is, in this case adsense#adClient.\"," +
            "\"default\":\"adsense#adClient\"},\"productCode\":{\"type\":\"string\",\"description\":\"This" +
            " ad client\'s product code, which corresponds to the PRODUCT_CODE report dimensio" +
            "n.\"},\"supportsReporting\":{\"type\":\"boolean\",\"description\":\"Whether this ad client" +
            " supports being reported on.\"}}},\"AdClients\":{\"id\":\"AdClients\",\"type\":\"object\",\"" +
            "properties\":{\"etag\":{\"type\":\"string\",\"description\":\"ETag of this response for ca" +
            "ching purposes.\"},\"items\":{\"type\":\"array\",\"description\":\"The ad clients returned" +
            " in this list response.\",\"items\":{\"$ref\":\"AdClient\"}},\"kind\":{\"type\":\"string\",\"d" +
            "escription\":\"Kind of list this is, in this case adsense#adClients.\",\"default\":\"a" +
            "dsense#adClients\"},\"nextPageToken\":{\"type\":\"string\",\"description\":\"Continuation " +
            "token used to page through ad clients. To retrieve the next page of results, set" +
            " the next request\'s \\\"pageToken\\\" value to this.\"}}},\"AdUnit\":{\"id\":\"AdUnit\",\"ty" +
            "pe\":\"object\",\"properties\":{\"code\":{\"type\":\"string\",\"description\":\"Identity code " +
            "of this ad unit, not necessarily unique across ad clients.\"},\"id\":{\"type\":\"strin" +
            "g\",\"description\":\"Unique identifier of this ad unit. This should be considered a" +
            "n opaque identifier; it is not safe to rely on it being in any particular format" +
            ".\"},\"kind\":{\"type\":\"string\",\"description\":\"Kind of resource this is, in this cas" +
            "e adsense#adUnit.\",\"default\":\"adsense#adUnit\"},\"name\":{\"type\":\"string\",\"descript" +
            "ion\":\"Name of this ad unit.\"},\"status\":{\"type\":\"string\",\"description\":\"Status of" +
            " this ad unit. Possible values are:\\nNEW: Indicates that the ad unit was created" +
            " within the last seven days and does not yet have any activity associated with i" +
            "t.\\n\\nACTIVE: Indicates that there has been activity on this ad unit in the last" +
            " seven days.\\n\\nINACTIVE: Indicates that there has been no activity on this ad u" +
            "nit in the last seven days.\"}}},\"AdUnits\":{\"id\":\"AdUnits\",\"type\":\"object\",\"prope" +
            "rties\":{\"etag\":{\"type\":\"string\",\"description\":\"ETag of this response for caching" +
            " purposes.\"},\"items\":{\"type\":\"array\",\"description\":\"The ad units returned in thi" +
            "s list response.\",\"items\":{\"$ref\":\"AdUnit\"}},\"kind\":{\"type\":\"string\",\"descriptio" +
            "n\":\"Kind of list this is, in this case adsense#adUnits.\",\"default\":\"adsense#adUn" +
            "its\"},\"nextPageToken\":{\"type\":\"string\",\"description\":\"Continuation token used to" +
            " page through ad units. To retrieve the next page of results, set the next reque" +
            "st\'s \\\"pageToken\\\" value to this.\"}}},\"AdsenseReportsGenerateResponse\":{\"id\":\"Ad" +
            "senseReportsGenerateResponse\",\"type\":\"object\",\"properties\":{\"averages\":{\"type\":\"" +
            "array\",\"description\":\"The averages of the report. This is the same length as any" +
            " other row in the report; cells corresponding to dimension columns are empty.\",\"" +
            "items\":{\"type\":\"string\"}},\"headers\":{\"type\":\"array\",\"description\":\"The header in" +
            "formation of the columns requested in the report. This is a list of headers; one" +
            " for each dimension in the request, followed by one for each metric in the reque" +
            "st.\",\"items\":{\"type\":\"object\",\"properties\":{\"currency\":{\"type\":\"string\",\"descrip" +
            "tion\":\"The currency of this column. Only present if the header type is METRIC_CU" +
            "RRENCY.\"},\"name\":{\"type\":\"string\",\"description\":\"The name of the header.\"},\"type" +
            "\":{\"type\":\"string\",\"description\":\"The type of the header; one of DIMENSION, METR" +
            "IC_TALLY, METRIC_RATIO, or METRIC_CURRENCY.\"}}}},\"kind\":{\"type\":\"string\",\"descri" +
            "ption\":\"Kind this is, in this case adsense#report.\",\"default\":\"adsense#report\"}," +
            "\"rows\":{\"type\":\"array\",\"description\":\"The output rows of the report. Each row is" +
            " a list of cells; one for each dimension in the request, followed by one for eac" +
            "h metric in the request. The dimension cells contain strings, and the metric cel" +
            "ls contain numbers.\",\"items\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"totalM" +
            "atchedRows\":{\"type\":\"string\",\"description\":\"The total number of rows matched by " +
            "the report request. Fewer rows may be returned in the response due to being limi" +
            "ted by the row count requested or the report row limit.\",\"format\":\"int64\"},\"tota" +
            "ls\":{\"type\":\"array\",\"description\":\"The totals of the report. This is the same le" +
            "ngth as any other row in the report; cells corresponding to dimension columns ar" +
            "e empty.\",\"items\":{\"type\":\"string\"}},\"warnings\":{\"type\":\"array\",\"description\":\"A" +
            "ny warnings associated with generation of the report.\",\"items\":{\"type\":\"string\"}" +
            "}}},\"CustomChannel\":{\"id\":\"CustomChannel\",\"type\":\"object\",\"properties\":{\"code\":{" +
            "\"type\":\"string\",\"description\":\"Code of this custom channel, not necessarily uniq" +
            "ue across ad clients.\"},\"id\":{\"type\":\"string\",\"description\":\"Unique identifier o" +
            "f this custom channel. This should be considered an opaque identifier; it is not" +
            " safe to rely on it being in any particular format.\"},\"kind\":{\"type\":\"string\",\"d" +
            "escription\":\"Kind of resource this is, in this case adsense#customChannel.\",\"def" +
            "ault\":\"adsense#customChannel\"},\"name\":{\"type\":\"string\",\"description\":\"Name of th" +
            "is custom channel.\"}}},\"CustomChannels\":{\"id\":\"CustomChannels\",\"type\":\"object\",\"" +
            "properties\":{\"etag\":{\"type\":\"string\",\"description\":\"ETag of this response for ca" +
            "ching purposes.\"},\"items\":{\"type\":\"array\",\"description\":\"The custom channels ret" +
            "urned in this list response.\",\"items\":{\"$ref\":\"CustomChannel\"}},\"kind\":{\"type\":\"" +
            "string\",\"description\":\"Kind of list this is, in this case adsense#customChannels" +
            ".\",\"default\":\"adsense#customChannels\"},\"nextPageToken\":{\"type\":\"string\",\"descrip" +
            "tion\":\"Continuation token used to page through custom channels. To retrieve the " +
            "next page of results, set the next request\'s \\\"pageToken\\\" value to this.\"}}},\"U" +
            "rlChannel\":{\"id\":\"UrlChannel\",\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string" +
            "\",\"description\":\"Unique identifier of this URL channel. This should be considere" +
            "d an opaque identifier; it is not safe to rely on it being in any particular for" +
            "mat.\"},\"kind\":{\"type\":\"string\",\"description\":\"Kind of resource this is, in this " +
            "case adsense#urlChannel.\",\"default\":\"adsense#urlChannel\"},\"urlPattern\":{\"type\":\"" +
            "string\",\"description\":\"URL Pattern of this URL channel. Does not include \\\"http:" +
            "//\\\" or \\\"https://\\\". Example: www.example.com/home\"}}},\"UrlChannels\":{\"id\":\"Url" +
            "Channels\",\"type\":\"object\",\"properties\":{\"etag\":{\"type\":\"string\",\"description\":\"E" +
            "Tag of this response for caching purposes.\"},\"items\":{\"type\":\"array\",\"descriptio" +
            "n\":\"The URL channels returned in this list response.\",\"items\":{\"$ref\":\"UrlChanne" +
            "l\"}},\"kind\":{\"type\":\"string\",\"description\":\"Kind of list this is, in this case a" +
            "dsense#urlChannels.\",\"default\":\"adsense#urlChannels\"},\"nextPageToken\":{\"type\":\"s" +
            "tring\",\"description\":\"Continuation token used to page through URL channels. To r" +
            "etrieve the next page of results, set the next request\'s \\\"pageToken\\\" value to " +
            "this.\"}}}},\"resources\":{\"adclients\":{\"methods\":{\"list\":{\"id\":\"adsense.adclients." +
            "list\",\"path\":\"adclients\",\"httpMethod\":\"GET\",\"description\":\"List all ad clients i" +
            "n this AdSense account.\",\"parameters\":{\"maxResults\":{\"type\":\"integer\",\"descripti" +
            "on\":\"The maximum number of ad clients to include in the response, used for pagin" +
            "g.\",\"format\":\"int32\",\"minimum\":\"0\",\"maximum\":\"10000\",\"location\":\"query\"},\"pageTo" +
            "ken\":{\"type\":\"string\",\"description\":\"A continuation token, used to page through " +
            "ad clients. To retrieve the next page, set this parameter to the value of \\\"next" +
            "PageToken\\\" from the previous response.\",\"location\":\"query\"}},\"response\":{\"$ref\"" +
            ":\"AdClients\"},\"scopes\":[\"https://www.googleapis.com/auth/adsense\",\"https://www.g" +
            "oogleapis.com/auth/adsense.readonly\"]}}},\"adunits\":{\"methods\":{\"list\":{\"id\":\"ads" +
            "ense.adunits.list\",\"path\":\"adclients/{adClientId}/adunits\",\"httpMethod\":\"GET\",\"d" +
            "escription\":\"List all ad units in this AdSense account.\",\"parameters\":{\"adClient" +
            "Id\":{\"type\":\"string\",\"description\":\"Ad client for which to list ad units.\",\"requ" +
            "ired\":true,\"location\":\"path\"},\"includeInactive\":{\"type\":\"boolean\",\"description\":" +
            "\"Whether to include inactive ad units. Default: true.\",\"location\":\"query\"},\"maxR" +
            "esults\":{\"type\":\"integer\",\"description\":\"The maximum number of ad units to inclu" +
            "de in the response, used for paging.\",\"format\":\"int32\",\"minimum\":\"0\",\"maximum\":\"" +
            "10000\",\"location\":\"query\"},\"pageToken\":{\"type\":\"string\",\"description\":\"A continu" +
            "ation token, used to page through ad units. To retrieve the next page, set this " +
            "parameter to the value of \\\"nextPageToken\\\" from the previous response.\",\"locati" +
            "on\":\"query\"}},\"parameterOrder\":[\"adClientId\"],\"response\":{\"$ref\":\"AdUnits\"},\"sco" +
            "pes\":[\"https://www.googleapis.com/auth/adsense\",\"https://www.googleapis.com/auth" +
            "/adsense.readonly\"]}}},\"customchannels\":{\"methods\":{\"list\":{\"id\":\"adsense.custom" +
            "channels.list\",\"path\":\"adclients/{adClientId}/customchannels\",\"httpMethod\":\"GET\"" +
            ",\"description\":\"List all custom channels in this AdSense account.\",\"parameters\":" +
            "{\"adClientId\":{\"type\":\"string\",\"description\":\"Ad client for which to list custom" +
            " channels.\",\"required\":true,\"location\":\"path\"},\"maxResults\":{\"type\":\"integer\",\"d" +
            "escription\":\"The maximum number of custom channels to include in the response, u" +
            "sed for paging.\",\"format\":\"int32\",\"minimum\":\"0\",\"maximum\":\"10000\",\"location\":\"qu" +
            "ery\"},\"pageToken\":{\"type\":\"string\",\"description\":\"A continuation token, used to " +
            "page through custom channels. To retrieve the next page, set this parameter to t" +
            "he value of \\\"nextPageToken\\\" from the previous response.\",\"location\":\"query\"}}," +
            "\"parameterOrder\":[\"adClientId\"],\"response\":{\"$ref\":\"CustomChannels\"},\"scopes\":[\"" +
            "https://www.googleapis.com/auth/adsense\",\"https://www.googleapis.com/auth/adsens" +
            "e.readonly\"]}}},\"reports\":{\"methods\":{\"generate\":{\"id\":\"adsense.reports.generate" +
            "\",\"path\":\"reports\",\"httpMethod\":\"GET\",\"description\":\"Generate an AdSense report " +
            "based on the report request sent in the query parameters. Returns the result as " +
            "JSON; to retrieve output in CSV format specify \\\"alt=csv\\\" as a query parameter." +
            "\",\"parameters\":{\"currency\":{\"type\":\"string\",\"description\":\"Optional currency to " +
            "use when reporting on monetary metrics. Defaults to the account\'s currency if no" +
            "t set.\",\"pattern\":\"[a-zA-Z]+\",\"location\":\"query\"},\"dimension\":{\"type\":\"string\",\"" +
            "description\":\"Dimensions to base the report on.\",\"pattern\":\"[a-zA-Z_]+\",\"repeate" +
            "d\":true,\"location\":\"query\"},\"endDate\":{\"type\":\"string\",\"description\":\"End of the" +
            " date range to report on in \\\"YYYY-MM-DD\\\" format, inclusive.\",\"required\":true,\"" +
            "pattern\":\"\\\\d{4}-\\\\d{2}-\\\\d{2}\",\"location\":\"query\"},\"filter\":{\"type\":\"string\",\"d" +
            "escription\":\"Filters to be run on the report.\",\"pattern\":\"[a-zA-Z_]+(==|=@).+\",\"" +
            "repeated\":true,\"location\":\"query\"},\"locale\":{\"type\":\"string\",\"description\":\"Opti" +
            "onal locale to use for translating report output to a local language. Defaults t" +
            "o \\\"en_US\\\" if not specified.\",\"pattern\":\"[a-zA-Z_]+\",\"location\":\"query\"},\"maxRe" +
            "sults\":{\"type\":\"integer\",\"description\":\"The maximum number of rows of report dat" +
            "a to return.\",\"format\":\"int32\",\"minimum\":\"0\",\"maximum\":\"50000\",\"location\":\"query" +
            "\"},\"metric\":{\"type\":\"string\",\"description\":\"Numeric columns to include in the re" +
            "port.\",\"pattern\":\"[a-zA-Z_]+\",\"repeated\":true,\"location\":\"query\"},\"sort\":{\"type\"" +
            ":\"string\",\"description\":\"The name of a dimension or metric to sort the resulting" +
            " report on, optionally prefixed with \\\"+\\\" to sort ascending or \\\"-\\\" to sort de" +
            "scending. If no prefix is specified, the column is sorted ascending.\",\"pattern\":" +
            "\"(\\\\+|-)?[a-zA-Z_]+\",\"repeated\":true,\"location\":\"query\"},\"startDate\":{\"type\":\"st" +
            "ring\",\"description\":\"Start of the date range to report on in \\\"YYYY-MM-DD\\\" form" +
            "at, inclusive.\",\"required\":true,\"pattern\":\"\\\\d{4}-\\\\d{2}-\\\\d{2}\",\"location\":\"que" +
            "ry\"},\"startIndex\":{\"type\":\"integer\",\"description\":\"Index of the first row of rep" +
            "ort data to return.\",\"format\":\"int32\",\"minimum\":\"0\",\"maximum\":\"5000\",\"location\":" +
            "\"query\"}},\"parameterOrder\":[\"startDate\",\"endDate\"],\"response\":{\"$ref\":\"AdsenseRe" +
            "portsGenerateResponse\"},\"scopes\":[\"https://www.googleapis.com/auth/adsense\",\"htt" +
            "ps://www.googleapis.com/auth/adsense.readonly\"]}}},\"urlchannels\":{\"methods\":{\"li" +
            "st\":{\"id\":\"adsense.urlchannels.list\",\"path\":\"adclients/{adClientId}/urlchannels\"" +
            ",\"httpMethod\":\"GET\",\"description\":\"List all URL channels in this AdSense account" +
            ".\",\"parameters\":{\"adClientId\":{\"type\":\"string\",\"description\":\"Ad client for whic" +
            "h to list URL channels.\",\"required\":true,\"location\":\"path\"},\"maxResults\":{\"type\"" +
            ":\"integer\",\"description\":\"The maximum number of URL channels to include in the r" +
            "esponse, used for paging.\",\"format\":\"int32\",\"minimum\":\"0\",\"maximum\":\"10000\",\"loc" +
            "ation\":\"query\"},\"pageToken\":{\"type\":\"string\",\"description\":\"A continuation token" +
            ", used to page through URL channels. To retrieve the next page, set this paramet" +
            "er to the value of \\\"nextPageToken\\\" from the previous response.\",\"location\":\"qu" +
            "ery\"}},\"parameterOrder\":[\"adClientId\"],\"response\":{\"$ref\":\"UrlChannels\"},\"scopes" +
            "\":[\"https://www.googleapis.com/auth/adsense\",\"https://www.googleapis.com/auth/ad" +
            "sense.readonly\"]}}}}}";
        
        private const string Version = "v1";
        
        private const string Name = "adsense";
        
        private const string BaseUri = "https://www.googleapis.com/adsense/v1/";
        
        private const Google.Apis.Discovery.DiscoveryVersion DiscoveryVersionUsed = Google.Apis.Discovery.DiscoveryVersion.Version_1_0;
        
        private string key;
        
        protected AdsenseService(Google.Apis.Discovery.IService genericService, Google.Apis.Authentication.IAuthenticator authenticator) {
            this.genericService = genericService;
            this.authenticator = authenticator;
            this.adclients = new AdclientsResource(this);
            this.adunits = new AdunitsResource(this);
            this.customchannels = new CustomchannelsResource(this);
            this.reports = new ReportsResource(this);
            this.urlchannels = new UrlchannelsResource(this);
        }
        
        public AdsenseService() : 
                this(Google.Apis.Authentication.NullAuthenticator.Instance) {
        }
        
        public AdsenseService(Google.Apis.Authentication.IAuthenticator authenticator) : 
                this(new Google.Apis.Discovery.DiscoveryService(new Google.Apis.Discovery.StringDiscoveryDevice(DiscoveryDocument)).GetService(AdsenseService.DiscoveryVersionUsed, new Google.Apis.Discovery.FactoryParameterV1_0(new System.Uri(AdsenseService.BaseUri))), authenticator) {
        }
        
        /// <summary>Sets the API-Key (or DeveloperKey) which this service uses for all requests</summary>
        public virtual string Key {
            get {
                return this.key;
            }
            set {
                this.key = value;
            }
        }
        
        public virtual Google.Apis.Requests.IRequest CreateRequest(string resource, string method) {
            Google.Apis.Requests.IRequest request = this.genericService.CreateRequest(resource, method);
            if (!string.IsNullOrEmpty(Key)) {
                request = request.WithKey(this.Key);
            }
            return request.WithAuthentication(authenticator);
        }
        
        public virtual void RegisterSerializer(Google.Apis.ISerializer serializer) {
            genericService.Serializer = serializer;
        }
        
        public virtual string SerializeObject(object obj) {
            return genericService.SerializeRequest(obj);
        }
        
        public virtual T DeserializeResponse<T>(Google.Apis.Requests.IResponse response)
         {
            return genericService.DeserializeResponse<T>(response);
        }
        
        /// <summary>A list of all OAuth2.0 scopes. Each of these scopes relates to a permission or group of permissions that different methods of this API may need.</summary>
        public enum Scopes {
            
            /// <summary>View and manage your AdSense data</summary>
            [Google.Apis.Util.StringValueAttribute("https://www.googleapis.com/auth/adsense")]
            Adsense,
            
            /// <summary>View your AdSense data</summary>
            [Google.Apis.Util.StringValueAttribute("https://www.googleapis.com/auth/adsense.readonly")]
            AdsenseReadonly,
        }
    }
    
    public class AdclientsResource {
        
        private Google.Apis.Discovery.IRequestProvider service;
        
        private const string Resource = "adclients";
        
        public AdclientsResource(AdsenseService service) {
            this.service = service;
        }
        
        /// <summary>List all ad clients in this AdSense account.</summary>
        public virtual ListRequest List() {
            return new ListRequest(service);
        }
        
        public class ListRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Adsense.v1.Data.AdClients> {
            
            private string oauth_token;
            
            private System.Boolean? prettyPrint;
            
            private string quotaUser;
            
            private System.Int64? maxResults;
            
            private string pageToken;
            
            public ListRequest(Google.Apis.Discovery.IRequestProvider service) : 
                    base(service) {
            }
            
            /// <summary>OAuth 2.0 token for the current user.</summary>
            [Google.Apis.Util.RequestParameterAttribute("oauth_token")]
            public virtual string Oauth_token {
                get {
                    return this.oauth_token;
                }
                set {
                    this.oauth_token = value;
                }
            }
            
            /// <summary>Returns response with indentations and line breaks.</summary>
            [Google.Apis.Util.RequestParameterAttribute("prettyPrint")]
            public virtual System.Boolean? PrettyPrint {
                get {
                    return this.prettyPrint;
                }
                set {
                    this.prettyPrint = value;
                }
            }
            
            /// <summary>Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</summary>
            [Google.Apis.Util.RequestParameterAttribute("quotaUser")]
            public virtual string QuotaUser {
                get {
                    return this.quotaUser;
                }
                set {
                    this.quotaUser = value;
                }
            }
            
            /// <summary>The maximum number of ad clients to include in the response, used for paging.</summary>
            [Google.Apis.Util.RequestParameterAttribute("maxResults")]
            public virtual System.Int64? MaxResults {
                get {
                    return this.maxResults;
                }
                set {
                    this.maxResults = value;
                }
            }
            
            /// <summary>A continuation token, used to page through ad clients. To retrieve the next page, set this parameter to the value of "nextPageToken" from the previous response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("pageToken")]
            public virtual string PageToken {
                get {
                    return this.pageToken;
                }
                set {
                    this.pageToken = value;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "adclients";
                }
            }
            
            protected override string MethodName {
                get {
                    return "list";
                }
            }
        }
    }
    
    public class AdunitsResource {
        
        private Google.Apis.Discovery.IRequestProvider service;
        
        private const string Resource = "adunits";
        
        public AdunitsResource(AdsenseService service) {
            this.service = service;
        }
        
        /// <summary>List all ad units in this AdSense account.</summary>
        /// <param name="adClientId">Required - Ad client for which to list ad units.</param>
        public virtual ListRequest List(string adClientId) {
            return new ListRequest(service, adClientId);
        }
        
        public class ListRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Adsense.v1.Data.AdUnits> {
            
            private string oauth_token;
            
            private System.Boolean? prettyPrint;
            
            private string quotaUser;
            
            private string adClientId;
            
            private System.Boolean? includeInactive;
            
            private System.Int64? maxResults;
            
            private string pageToken;
            
            public ListRequest(Google.Apis.Discovery.IRequestProvider service, string adClientId) : 
                    base(service) {
                this.adClientId = adClientId;
            }
            
            /// <summary>OAuth 2.0 token for the current user.</summary>
            [Google.Apis.Util.RequestParameterAttribute("oauth_token")]
            public virtual string Oauth_token {
                get {
                    return this.oauth_token;
                }
                set {
                    this.oauth_token = value;
                }
            }
            
            /// <summary>Returns response with indentations and line breaks.</summary>
            [Google.Apis.Util.RequestParameterAttribute("prettyPrint")]
            public virtual System.Boolean? PrettyPrint {
                get {
                    return this.prettyPrint;
                }
                set {
                    this.prettyPrint = value;
                }
            }
            
            /// <summary>Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</summary>
            [Google.Apis.Util.RequestParameterAttribute("quotaUser")]
            public virtual string QuotaUser {
                get {
                    return this.quotaUser;
                }
                set {
                    this.quotaUser = value;
                }
            }
            
            /// <summary>Ad client for which to list ad units.</summary>
            [Google.Apis.Util.RequestParameterAttribute("adClientId")]
            public virtual string AdClientId {
                get {
                    return this.adClientId;
                }
            }
            
            /// <summary>Whether to include inactive ad units. Default: true.</summary>
            [Google.Apis.Util.RequestParameterAttribute("includeInactive")]
            public virtual System.Boolean? IncludeInactive {
                get {
                    return this.includeInactive;
                }
                set {
                    this.includeInactive = value;
                }
            }
            
            /// <summary>The maximum number of ad units to include in the response, used for paging.</summary>
            [Google.Apis.Util.RequestParameterAttribute("maxResults")]
            public virtual System.Int64? MaxResults {
                get {
                    return this.maxResults;
                }
                set {
                    this.maxResults = value;
                }
            }
            
            /// <summary>A continuation token, used to page through ad units. To retrieve the next page, set this parameter to the value of "nextPageToken" from the previous response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("pageToken")]
            public virtual string PageToken {
                get {
                    return this.pageToken;
                }
                set {
                    this.pageToken = value;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "adunits";
                }
            }
            
            protected override string MethodName {
                get {
                    return "list";
                }
            }
        }
    }
    
    public class CustomchannelsResource {
        
        private Google.Apis.Discovery.IRequestProvider service;
        
        private const string Resource = "customchannels";
        
        public CustomchannelsResource(AdsenseService service) {
            this.service = service;
        }
        
        /// <summary>List all custom channels in this AdSense account.</summary>
        /// <param name="adClientId">Required - Ad client for which to list custom channels.</param>
        public virtual ListRequest List(string adClientId) {
            return new ListRequest(service, adClientId);
        }
        
        public class ListRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Adsense.v1.Data.CustomChannels> {
            
            private string oauth_token;
            
            private System.Boolean? prettyPrint;
            
            private string quotaUser;
            
            private string adClientId;
            
            private System.Int64? maxResults;
            
            private string pageToken;
            
            public ListRequest(Google.Apis.Discovery.IRequestProvider service, string adClientId) : 
                    base(service) {
                this.adClientId = adClientId;
            }
            
            /// <summary>OAuth 2.0 token for the current user.</summary>
            [Google.Apis.Util.RequestParameterAttribute("oauth_token")]
            public virtual string Oauth_token {
                get {
                    return this.oauth_token;
                }
                set {
                    this.oauth_token = value;
                }
            }
            
            /// <summary>Returns response with indentations and line breaks.</summary>
            [Google.Apis.Util.RequestParameterAttribute("prettyPrint")]
            public virtual System.Boolean? PrettyPrint {
                get {
                    return this.prettyPrint;
                }
                set {
                    this.prettyPrint = value;
                }
            }
            
            /// <summary>Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</summary>
            [Google.Apis.Util.RequestParameterAttribute("quotaUser")]
            public virtual string QuotaUser {
                get {
                    return this.quotaUser;
                }
                set {
                    this.quotaUser = value;
                }
            }
            
            /// <summary>Ad client for which to list custom channels.</summary>
            [Google.Apis.Util.RequestParameterAttribute("adClientId")]
            public virtual string AdClientId {
                get {
                    return this.adClientId;
                }
            }
            
            /// <summary>The maximum number of custom channels to include in the response, used for paging.</summary>
            [Google.Apis.Util.RequestParameterAttribute("maxResults")]
            public virtual System.Int64? MaxResults {
                get {
                    return this.maxResults;
                }
                set {
                    this.maxResults = value;
                }
            }
            
            /// <summary>A continuation token, used to page through custom channels. To retrieve the next page, set this parameter to the value of "nextPageToken" from the previous response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("pageToken")]
            public virtual string PageToken {
                get {
                    return this.pageToken;
                }
                set {
                    this.pageToken = value;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "customchannels";
                }
            }
            
            protected override string MethodName {
                get {
                    return "list";
                }
            }
        }
    }
    
    public class ReportsResource {
        
        private Google.Apis.Discovery.IRequestProvider service;
        
        private const string Resource = "reports";
        
        public ReportsResource(AdsenseService service) {
            this.service = service;
        }
        
        /// <summary>Generate an AdSense report based on the report request sent in the query parameters. Returns the result as JSON; to retrieve output in CSV format specify &quot;alt=csv&quot; as a query parameter.</summary>
        /// <param name="startDate">Required - Must match pattern \d{4}-\d{2}-\d{2} - Start of the date range to report on in &quot;YYYY-MM-DD&quot; format, inclusive.</param>
        /// <param name="endDate">Required - Must match pattern \d{4}-\d{2}-\d{2} - End of the date range to report on in &quot;YYYY-MM-DD&quot; format, inclusive.</param>
        public virtual GenerateRequest Generate(string startDate, string endDate) {
            return new GenerateRequest(service, startDate, endDate);
        }
        
        public class GenerateRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Adsense.v1.Data.AdsenseReportsGenerateResponse> {
            
            private string oauth_token;
            
            private System.Boolean? prettyPrint;
            
            private string quotaUser;
            
            private string currency;
            
            private Google.Apis.Util.Repeatable<string> dimension;
            
            private string endDate;
            
            private Google.Apis.Util.Repeatable<string> filter;
            
            private string locale;
            
            private System.Int64? maxResults;
            
            private Google.Apis.Util.Repeatable<string> metric;
            
            private Google.Apis.Util.Repeatable<string> sort;
            
            private string startDate;
            
            private System.Int64? startIndex;
            
            public GenerateRequest(Google.Apis.Discovery.IRequestProvider service, string startDate, string endDate) : 
                    base(service) {
                this.startDate = startDate;
                this.endDate = endDate;
            }
            
            /// <summary>OAuth 2.0 token for the current user.</summary>
            [Google.Apis.Util.RequestParameterAttribute("oauth_token")]
            public virtual string Oauth_token {
                get {
                    return this.oauth_token;
                }
                set {
                    this.oauth_token = value;
                }
            }
            
            /// <summary>Returns response with indentations and line breaks.</summary>
            [Google.Apis.Util.RequestParameterAttribute("prettyPrint")]
            public virtual System.Boolean? PrettyPrint {
                get {
                    return this.prettyPrint;
                }
                set {
                    this.prettyPrint = value;
                }
            }
            
            /// <summary>Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</summary>
            [Google.Apis.Util.RequestParameterAttribute("quotaUser")]
            public virtual string QuotaUser {
                get {
                    return this.quotaUser;
                }
                set {
                    this.quotaUser = value;
                }
            }
            
            /// <summary>Optional currency to use when reporting on monetary metrics. Defaults to the account's currency if not set.</summary>
            [Google.Apis.Util.RequestParameterAttribute("currency")]
            public virtual string Currency {
                get {
                    return this.currency;
                }
                set {
                    this.currency = value;
                }
            }
            
            /// <summary>Dimensions to base the report on.</summary>
            [Google.Apis.Util.RequestParameterAttribute("dimension")]
            public virtual Google.Apis.Util.Repeatable<string> Dimension {
                get {
                    return this.dimension;
                }
                set {
                    this.dimension = value;
                }
            }
            
            /// <summary>End of the date range to report on in "YYYY-MM-DD" format, inclusive.</summary>
            [Google.Apis.Util.RequestParameterAttribute("endDate")]
            public virtual string EndDate {
                get {
                    return this.endDate;
                }
            }
            
            /// <summary>Filters to be run on the report.</summary>
            [Google.Apis.Util.RequestParameterAttribute("filter")]
            public virtual Google.Apis.Util.Repeatable<string> Filter {
                get {
                    return this.filter;
                }
                set {
                    this.filter = value;
                }
            }
            
            /// <summary>Optional locale to use for translating report output to a local language. Defaults to "en_US" if not specified.</summary>
            [Google.Apis.Util.RequestParameterAttribute("locale")]
            public virtual string Locale {
                get {
                    return this.locale;
                }
                set {
                    this.locale = value;
                }
            }
            
            /// <summary>The maximum number of rows of report data to return.</summary>
            [Google.Apis.Util.RequestParameterAttribute("maxResults")]
            public virtual System.Int64? MaxResults {
                get {
                    return this.maxResults;
                }
                set {
                    this.maxResults = value;
                }
            }
            
            /// <summary>Numeric columns to include in the report.</summary>
            [Google.Apis.Util.RequestParameterAttribute("metric")]
            public virtual Google.Apis.Util.Repeatable<string> Metric {
                get {
                    return this.metric;
                }
                set {
                    this.metric = value;
                }
            }
            
            /// <summary>The name of a dimension or metric to sort the resulting report on, optionally prefixed with "+" to sort ascending or "-" to sort descending. If no prefix is specified, the column is sorted ascending.</summary>
            [Google.Apis.Util.RequestParameterAttribute("sort")]
            public virtual Google.Apis.Util.Repeatable<string> Sort {
                get {
                    return this.sort;
                }
                set {
                    this.sort = value;
                }
            }
            
            /// <summary>Start of the date range to report on in "YYYY-MM-DD" format, inclusive.</summary>
            [Google.Apis.Util.RequestParameterAttribute("startDate")]
            public virtual string StartDate {
                get {
                    return this.startDate;
                }
            }
            
            /// <summary>Index of the first row of report data to return.</summary>
            [Google.Apis.Util.RequestParameterAttribute("startIndex")]
            public virtual System.Int64? StartIndex {
                get {
                    return this.startIndex;
                }
                set {
                    this.startIndex = value;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "reports";
                }
            }
            
            protected override string MethodName {
                get {
                    return "generate";
                }
            }
        }
    }
    
    public class UrlchannelsResource {
        
        private Google.Apis.Discovery.IRequestProvider service;
        
        private const string Resource = "urlchannels";
        
        public UrlchannelsResource(AdsenseService service) {
            this.service = service;
        }
        
        /// <summary>List all URL channels in this AdSense account.</summary>
        /// <param name="adClientId">Required - Ad client for which to list URL channels.</param>
        public virtual ListRequest List(string adClientId) {
            return new ListRequest(service, adClientId);
        }
        
        public class ListRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Adsense.v1.Data.UrlChannels> {
            
            private string oauth_token;
            
            private System.Boolean? prettyPrint;
            
            private string quotaUser;
            
            private string adClientId;
            
            private System.Int64? maxResults;
            
            private string pageToken;
            
            public ListRequest(Google.Apis.Discovery.IRequestProvider service, string adClientId) : 
                    base(service) {
                this.adClientId = adClientId;
            }
            
            /// <summary>OAuth 2.0 token for the current user.</summary>
            [Google.Apis.Util.RequestParameterAttribute("oauth_token")]
            public virtual string Oauth_token {
                get {
                    return this.oauth_token;
                }
                set {
                    this.oauth_token = value;
                }
            }
            
            /// <summary>Returns response with indentations and line breaks.</summary>
            [Google.Apis.Util.RequestParameterAttribute("prettyPrint")]
            public virtual System.Boolean? PrettyPrint {
                get {
                    return this.prettyPrint;
                }
                set {
                    this.prettyPrint = value;
                }
            }
            
            /// <summary>Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</summary>
            [Google.Apis.Util.RequestParameterAttribute("quotaUser")]
            public virtual string QuotaUser {
                get {
                    return this.quotaUser;
                }
                set {
                    this.quotaUser = value;
                }
            }
            
            /// <summary>Ad client for which to list URL channels.</summary>
            [Google.Apis.Util.RequestParameterAttribute("adClientId")]
            public virtual string AdClientId {
                get {
                    return this.adClientId;
                }
            }
            
            /// <summary>The maximum number of URL channels to include in the response, used for paging.</summary>
            [Google.Apis.Util.RequestParameterAttribute("maxResults")]
            public virtual System.Int64? MaxResults {
                get {
                    return this.maxResults;
                }
                set {
                    this.maxResults = value;
                }
            }
            
            /// <summary>A continuation token, used to page through URL channels. To retrieve the next page, set this parameter to the value of "nextPageToken" from the previous response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("pageToken")]
            public virtual string PageToken {
                get {
                    return this.pageToken;
                }
                set {
                    this.pageToken = value;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "urlchannels";
                }
            }
            
            protected override string MethodName {
                get {
                    return "list";
                }
            }
        }
    }
    
    public partial class AdsenseService {
        
        private const string Resource = "";
        
        private AdclientsResource adclients;
        
        private AdunitsResource adunits;
        
        private CustomchannelsResource customchannels;
        
        private ReportsResource reports;
        
        private UrlchannelsResource urlchannels;
        
        private Google.Apis.Discovery.IRequestProvider service {
            get {
                return this;
            }
        }
        
        public virtual AdclientsResource Adclients {
            get {
                return this.adclients;
            }
        }
        
        public virtual AdunitsResource Adunits {
            get {
                return this.adunits;
            }
        }
        
        public virtual CustomchannelsResource Customchannels {
            get {
                return this.customchannels;
            }
        }
        
        public virtual ReportsResource Reports {
            get {
                return this.reports;
            }
        }
        
        public virtual UrlchannelsResource Urlchannels {
            get {
                return this.urlchannels;
            }
        }
    }
}
