//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Google.Apis.Androidpublisher.v1.Data {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    
    
    /// <summary>A Purchase resource indicates the status of a user&apos;s subscription purchase.</summary>
    public class SubscriptionPurchase : Google.Apis.Requests.IDirectResponseSchema {
        
        private System.Nullable<bool> _autoRenewing;
        
        private string _initiationTimestampMsec;
        
        private string _kind;
        
        private string _validUntilTimestampMsec;
        
        private string _ETag;
        
        /// <summary>Whether the subscription will automatically be renewed when it reaches its current expiry time.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("autoRenewing")]
        public virtual System.Nullable<bool> AutoRenewing {
            get {
                return this._autoRenewing;
            }
            set {
                this._autoRenewing = value;
            }
        }
        
        /// <summary>Time at which the subscription was granted, in milliseconds since Epoch.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("initiationTimestampMsec")]
        public virtual string InitiationTimestampMsec {
            get {
                return this._initiationTimestampMsec;
            }
            set {
                this._initiationTimestampMsec = value;
            }
        }
        
        /// <summary>This kind represents a subscriptionPurchase object in the androidpublisher service.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this._kind;
            }
            set {
                this._kind = value;
            }
        }
        
        /// <summary>Time at which the subscription will expire, in milliseconds since Epoch.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("validUntilTimestampMsec")]
        public virtual string ValidUntilTimestampMsec {
            get {
                return this._validUntilTimestampMsec;
            }
            set {
                this._validUntilTimestampMsec = value;
            }
        }
        
        public virtual string ETag {
            get {
                return this._ETag;
            }
            set {
                this._ETag = value;
            }
        }
    }
}
namespace Google.Apis.Androidpublisher.v1 {
    using System;
    using System.IO;
    using System.Collections.Generic;
    using Google.Apis;
    using Google.Apis.Discovery;
    
    
    public partial class AndroidpublisherService : Google.Apis.Services.BaseClientService {
        
        public const string Version = "v1";
        
        public static Google.Apis.Discovery.DiscoveryVersion DiscoveryVersionUsed = Google.Apis.Discovery.DiscoveryVersion.Version_1_0;
        
        private System.Collections.Generic.IDictionary<string, Google.Apis.Discovery.IParameter> _serviceParameters;
        
        public AndroidpublisherService(Google.Apis.Services.BaseClientService.Initializer initializer) : 
                base(initializer) {
            this._purchases = new PurchasesResource(this, Authenticator);
            this.InitParameters();
        }
        
        public AndroidpublisherService() : 
                this(new Google.Apis.Services.BaseClientService.Initializer()) {
        }
        
        public override System.Collections.Generic.IList<string> Features {
            get {
                return new string[0];
            }
        }
        
        public override string Name {
            get {
                return "androidpublisher";
            }
        }
        
        public override string BaseUri {
            get {
                return "https://www.googleapis.com/androidpublisher/v1/applications/";
            }
        }
        
        public override System.Collections.Generic.IDictionary<string, Google.Apis.Discovery.IParameter> ServiceParameters {
            get {
                return this._serviceParameters;
            }
        }
        
        public override Google.Apis.Requests.IRequest CreateRequest(Google.Apis.Requests.IClientServiceRequest serviceRequest) {
            Google.Apis.Requests.IRequest request = Google.Apis.Requests.Request.CreateRequest(this, serviceRequest);
            if ((string.IsNullOrEmpty(ApiKey) == false)) {
                request = request.WithKey(this.ApiKey);
            }
            return request.WithAuthentication(Authenticator);
        }
        
        private void InitParameters() {
            System.Collections.Generic.Dictionary<string, Google.Apis.Discovery.IParameter> parameters = new System.Collections.Generic.Dictionary<string, Google.Apis.Discovery.IParameter>();
            parameters.Add("alt", Google.Apis.Util.Utilities.CreateRuntimeParameter("alt", false, "query", "json", null, new string[] {
                            "json"}));
            parameters.Add("fields", Google.Apis.Util.Utilities.CreateRuntimeParameter("fields", false, "query", null, null, new string[0]));
            parameters.Add("key", Google.Apis.Util.Utilities.CreateRuntimeParameter("key", false, "query", null, null, new string[0]));
            parameters.Add("oauth_token", Google.Apis.Util.Utilities.CreateRuntimeParameter("oauth_token", false, "query", null, null, new string[0]));
            parameters.Add("prettyPrint", Google.Apis.Util.Utilities.CreateRuntimeParameter("prettyPrint", false, "query", "true", null, new string[0]));
            parameters.Add("quotaUser", Google.Apis.Util.Utilities.CreateRuntimeParameter("quotaUser", false, "query", null, null, new string[0]));
            parameters.Add("userIp", Google.Apis.Util.Utilities.CreateRuntimeParameter("userIp", false, "query", null, null, new string[0]));
            this._serviceParameters = new Google.Apis.Util.ReadOnlyDictionary<string, Google.Apis.Discovery.IParameter>(parameters);
        }
    }
    
    public class PurchasesResource {
        
        private AndroidpublisherService service;
        
        private Google.Apis.Authentication.IAuthenticator authenticator;
        
        private const string Resource = "purchases";
        
        public PurchasesResource(AndroidpublisherService service, Google.Apis.Authentication.IAuthenticator authenticator) {
            this.service = service;
            this.authenticator = authenticator;
        }
        
        /// <summary>Cancels a user&apos;s subscription purchase. The subscription remains valid until its expiration time.</summary>
        /// <param name="packageName">Required - The package name of the application for which this subscription was purchased (for example, &apos;com.some.thing&apos;).</param>
        /// <param name="subscriptionId">Required - The purchased subscription ID (for example, &apos;monthly001&apos;).</param>
        /// <param name="token">Required - The token provided to the user&apos;s device when the subscription was purchased.</param>
        public virtual CancelRequest Cancel(string packageName, string subscriptionId, string token) {
            return new CancelRequest(service, packageName, subscriptionId, token);
        }
        
        /// <summary>Checks whether a user&apos;s subscription purchase is valid and returns its expiry time.</summary>
        /// <param name="packageName">Required - The package name of the application for which this subscription was purchased (for example, &apos;com.some.thing&apos;).</param>
        /// <param name="subscriptionId">Required - The purchased subscription ID (for example, &apos;monthly001&apos;).</param>
        /// <param name="token">Required - The token provided to the user&apos;s device when the subscription was purchased.</param>
        public virtual GetRequest Get(string packageName, string subscriptionId, string token) {
            return new GetRequest(service, packageName, subscriptionId, token);
        }
        
        public class CancelRequest : Google.Apis.Requests.ClientServiceRequest<string> {
            
            private string _alt;
            
            private string _fields;
            
            private string _oauth_token;
            
            private System.Nullable<bool> _prettyPrint;
            
            private string _quotaUser;
            
            private string _userIp;
            
            private string _packageName;
            
            private string _subscriptionId;
            
            private string _token;
            
            public CancelRequest(Google.Apis.Services.IClientService service, string packageName, string subscriptionId, string token) : 
                    base(service) {
                this._packageName = packageName;
                this._subscriptionId = subscriptionId;
                this._token = token;
                this.InitParameters();
            }
            
            /// <summary>Data format for the response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("alt", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Alt {
                get {
                    return this._alt;
                }
                set {
                    this._alt = value;
                }
            }
            
            /// <summary>Selector specifying which fields to include in a partial response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("fields", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Fields {
                get {
                    return this._fields;
                }
                set {
                    this._fields = value;
                }
            }
            
            /// <summary>OAuth 2.0 token for the current user.</summary>
            [Google.Apis.Util.RequestParameterAttribute("oauth_token", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Oauth_token {
                get {
                    return this._oauth_token;
                }
                set {
                    this._oauth_token = value;
                }
            }
            
            /// <summary>Returns response with indentations and line breaks.</summary>
            [Google.Apis.Util.RequestParameterAttribute("prettyPrint", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> PrettyPrint {
                get {
                    return this._prettyPrint;
                }
                set {
                    this._prettyPrint = value;
                }
            }
            
            /// <summary>Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</summary>
            [Google.Apis.Util.RequestParameterAttribute("quotaUser", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string QuotaUser {
                get {
                    return this._quotaUser;
                }
                set {
                    this._quotaUser = value;
                }
            }
            
            /// <summary>IP address of the site where the request originates. Use this if you want to enforce per-user limits.</summary>
            [Google.Apis.Util.RequestParameterAttribute("userIp", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string UserIp {
                get {
                    return this._userIp;
                }
                set {
                    this._userIp = value;
                }
            }
            
            /// <summary>The package name of the application for which this subscription was purchased (for example, 'com.some.thing').</summary>
            [Google.Apis.Util.RequestParameterAttribute("packageName", Google.Apis.Util.RequestParameterType.Path)]
            public virtual string PackageName {
                get {
                    return this._packageName;
                }
            }
            
            /// <summary>The purchased subscription ID (for example, 'monthly001').</summary>
            [Google.Apis.Util.RequestParameterAttribute("subscriptionId", Google.Apis.Util.RequestParameterType.Path)]
            public virtual string SubscriptionId {
                get {
                    return this._subscriptionId;
                }
            }
            
            /// <summary>The token provided to the user's device when the subscription was purchased.</summary>
            [Google.Apis.Util.RequestParameterAttribute("token", Google.Apis.Util.RequestParameterType.Path)]
            public virtual string Token {
                get {
                    return this._token;
                }
            }
            
            public override string ResourcePath {
                get {
                    return "purchases";
                }
            }
            
            public override string MethodName {
                get {
                    return "cancel";
                }
            }
            
            public override string HttpMethod {
                get {
                    return "POST";
                }
            }
            
            public override string RestPath {
                get {
                    return "{packageName}/subscriptions/{subscriptionId}/purchases/{token}/cancel";
                }
            }
            
            private void InitParameters() {
                System.Collections.Generic.Dictionary<string, Google.Apis.Discovery.IParameter> parameters = new System.Collections.Generic.Dictionary<string, Google.Apis.Discovery.IParameter>();
                parameters.Add("packageName", Google.Apis.Util.Utilities.CreateRuntimeParameter("packageName", true, "path", null, null, new string[0]));
                parameters.Add("subscriptionId", Google.Apis.Util.Utilities.CreateRuntimeParameter("subscriptionId", true, "path", null, null, new string[0]));
                parameters.Add("token", Google.Apis.Util.Utilities.CreateRuntimeParameter("token", true, "path", null, null, new string[0]));
                this._requestParameters = new Google.Apis.Util.ReadOnlyDictionary<string, Google.Apis.Discovery.IParameter>(parameters);
            }
        }
        
        public class GetRequest : Google.Apis.Requests.ClientServiceRequest<Google.Apis.Androidpublisher.v1.Data.SubscriptionPurchase> {
            
            private string _alt;
            
            private string _fields;
            
            private string _oauth_token;
            
            private System.Nullable<bool> _prettyPrint;
            
            private string _quotaUser;
            
            private string _userIp;
            
            private string _packageName;
            
            private string _subscriptionId;
            
            private string _token;
            
            public GetRequest(Google.Apis.Services.IClientService service, string packageName, string subscriptionId, string token) : 
                    base(service) {
                this._packageName = packageName;
                this._subscriptionId = subscriptionId;
                this._token = token;
                this.InitParameters();
            }
            
            /// <summary>Data format for the response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("alt", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Alt {
                get {
                    return this._alt;
                }
                set {
                    this._alt = value;
                }
            }
            
            /// <summary>Selector specifying which fields to include in a partial response.</summary>
            [Google.Apis.Util.RequestParameterAttribute("fields", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Fields {
                get {
                    return this._fields;
                }
                set {
                    this._fields = value;
                }
            }
            
            /// <summary>OAuth 2.0 token for the current user.</summary>
            [Google.Apis.Util.RequestParameterAttribute("oauth_token", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Oauth_token {
                get {
                    return this._oauth_token;
                }
                set {
                    this._oauth_token = value;
                }
            }
            
            /// <summary>Returns response with indentations and line breaks.</summary>
            [Google.Apis.Util.RequestParameterAttribute("prettyPrint", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> PrettyPrint {
                get {
                    return this._prettyPrint;
                }
                set {
                    this._prettyPrint = value;
                }
            }
            
            /// <summary>Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</summary>
            [Google.Apis.Util.RequestParameterAttribute("quotaUser", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string QuotaUser {
                get {
                    return this._quotaUser;
                }
                set {
                    this._quotaUser = value;
                }
            }
            
            /// <summary>IP address of the site where the request originates. Use this if you want to enforce per-user limits.</summary>
            [Google.Apis.Util.RequestParameterAttribute("userIp", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string UserIp {
                get {
                    return this._userIp;
                }
                set {
                    this._userIp = value;
                }
            }
            
            /// <summary>The package name of the application for which this subscription was purchased (for example, 'com.some.thing').</summary>
            [Google.Apis.Util.RequestParameterAttribute("packageName", Google.Apis.Util.RequestParameterType.Path)]
            public virtual string PackageName {
                get {
                    return this._packageName;
                }
            }
            
            /// <summary>The purchased subscription ID (for example, 'monthly001').</summary>
            [Google.Apis.Util.RequestParameterAttribute("subscriptionId", Google.Apis.Util.RequestParameterType.Path)]
            public virtual string SubscriptionId {
                get {
                    return this._subscriptionId;
                }
            }
            
            /// <summary>The token provided to the user's device when the subscription was purchased.</summary>
            [Google.Apis.Util.RequestParameterAttribute("token", Google.Apis.Util.RequestParameterType.Path)]
            public virtual string Token {
                get {
                    return this._token;
                }
            }
            
            public override string ResourcePath {
                get {
                    return "purchases";
                }
            }
            
            public override string MethodName {
                get {
                    return "get";
                }
            }
            
            public override string HttpMethod {
                get {
                    return "GET";
                }
            }
            
            public override string RestPath {
                get {
                    return "{packageName}/subscriptions/{subscriptionId}/purchases/{token}";
                }
            }
            
            private void InitParameters() {
                System.Collections.Generic.Dictionary<string, Google.Apis.Discovery.IParameter> parameters = new System.Collections.Generic.Dictionary<string, Google.Apis.Discovery.IParameter>();
                parameters.Add("packageName", Google.Apis.Util.Utilities.CreateRuntimeParameter("packageName", true, "path", null, null, new string[0]));
                parameters.Add("subscriptionId", Google.Apis.Util.Utilities.CreateRuntimeParameter("subscriptionId", true, "path", null, null, new string[0]));
                parameters.Add("token", Google.Apis.Util.Utilities.CreateRuntimeParameter("token", true, "path", null, null, new string[0]));
                this._requestParameters = new Google.Apis.Util.ReadOnlyDictionary<string, Google.Apis.Discovery.IParameter>(parameters);
            }
        }
    }
    
    public partial class AndroidpublisherService {
        
        private const string Resource = "";
        
        private PurchasesResource _purchases;
        
        private Google.Apis.Services.IClientService service {
            get {
                return this;
            }
        }
        
        public virtual PurchasesResource Purchases {
            get {
                return this._purchases;
            }
        }
    }
}
