//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Google.Apis.Plus.v1moments.Data {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    
    
    public class ItemScope {
        
        private ItemScope _about;
        
        private System.Collections.Generic.IList<string> _additionalName;
        
        private ItemScope _address;
        
        private string _addressCountry;
        
        private string _addressLocality;
        
        private string _addressRegion;
        
        private System.Collections.Generic.IList<ItemScope> _associated_media;
        
        private System.Nullable<long> _attendeeCount;
        
        private System.Collections.Generic.IList<ItemScope> _attendees;
        
        private ItemScope _audio;
        
        private System.Collections.Generic.IList<ItemScope> _author;
        
        private string _bestRating;
        
        private string _birthDate;
        
        private ItemScope _byArtist;
        
        private string _caption;
        
        private string _contentSize;
        
        private string _contentUrl;
        
        private System.Collections.Generic.IList<ItemScope> _contributor;
        
        private string _dateCreated;
        
        private string _dateModified;
        
        private string _datePublished;
        
        private string _description;
        
        private string _duration;
        
        private string _embedUrl;
        
        private string _endDate;
        
        private string _familyName;
        
        private string _gender;
        
        private ItemScope _geo;
        
        private string _givenName;
        
        private string _height;
        
        private string _id;
        
        private string _image;
        
        private ItemScope _inAlbum;
        
        private string _kind;
        
        private System.Nullable<double> _latitude;
        
        private ItemScope _location;
        
        private System.Nullable<double> _longitude;
        
        private string _name;
        
        private ItemScope _partOfTVSeries;
        
        private System.Collections.Generic.IList<ItemScope> _performers;
        
        private string _playerType;
        
        private string _postOfficeBoxNumber;
        
        private string _postalCode;
        
        private string _ratingValue;
        
        private System.Collections.Generic.IList<ItemScope> _reviewRating;
        
        private string _startDate;
        
        private string _streetAddress;
        
        private string _text;
        
        private ItemScope _thumbnail;
        
        private string _thumbnailUrl;
        
        private string _tickerSymbol;
        
        private string _type;
        
        private string _url;
        
        private string _width;
        
        private string _worstRating;
        
        [Newtonsoft.Json.JsonPropertyAttribute("about")]
        public virtual ItemScope About {
            get {
                return this._about;
            }
            set {
                this._about = value;
            }
        }
        
        /// <summary>An additional name for a Person, can be used for a middle name.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("additionalName")]
        public virtual System.Collections.Generic.IList<string> AdditionalName {
            get {
                return this._additionalName;
            }
            set {
                this._additionalName = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("address")]
        public virtual ItemScope Address {
            get {
                return this._address;
            }
            set {
                this._address = value;
            }
        }
        
        /// <summary>Address country.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("addressCountry")]
        public virtual string AddressCountry {
            get {
                return this._addressCountry;
            }
            set {
                this._addressCountry = value;
            }
        }
        
        /// <summary>Address locality.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("addressLocality")]
        public virtual string AddressLocality {
            get {
                return this._addressLocality;
            }
            set {
                this._addressLocality = value;
            }
        }
        
        /// <summary>Address region.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("addressRegion")]
        public virtual string AddressRegion {
            get {
                return this._addressRegion;
            }
            set {
                this._addressRegion = value;
            }
        }
        
        /// <summary>The encoding.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("associated_media")]
        public virtual System.Collections.Generic.IList<ItemScope> Associated_media {
            get {
                return this._associated_media;
            }
            set {
                this._associated_media = value;
            }
        }
        
        /// <summary>Number of attendees.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("attendeeCount")]
        public virtual System.Nullable<long> AttendeeCount {
            get {
                return this._attendeeCount;
            }
            set {
                this._attendeeCount = value;
            }
        }
        
        /// <summary>A person attending the event.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("attendees")]
        public virtual System.Collections.Generic.IList<ItemScope> Attendees {
            get {
                return this._attendees;
            }
            set {
                this._attendees = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("audio")]
        public virtual ItemScope Audio {
            get {
                return this._audio;
            }
            set {
                this._audio = value;
            }
        }
        
        /// <summary>The person who created this scope.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("author")]
        public virtual System.Collections.Generic.IList<ItemScope> Author {
            get {
                return this._author;
            }
            set {
                this._author = value;
            }
        }
        
        /// <summary>Best possible rating value.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("bestRating")]
        public virtual string BestRating {
            get {
                return this._bestRating;
            }
            set {
                this._bestRating = value;
            }
        }
        
        /// <summary>Date of birth.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("birthDate")]
        public virtual string BirthDate {
            get {
                return this._birthDate;
            }
            set {
                this._birthDate = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("byArtist")]
        public virtual ItemScope ByArtist {
            get {
                return this._byArtist;
            }
            set {
                this._byArtist = value;
            }
        }
        
        /// <summary>The caption for this object.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("caption")]
        public virtual string Caption {
            get {
                return this._caption;
            }
            set {
                this._caption = value;
            }
        }
        
        /// <summary>File size in (mega/kilo) bytes.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("contentSize")]
        public virtual string ContentSize {
            get {
                return this._contentSize;
            }
            set {
                this._contentSize = value;
            }
        }
        
        /// <summary>Actual bytes of the media object, for example the image file or video file.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("contentUrl")]
        public virtual string ContentUrl {
            get {
                return this._contentUrl;
            }
            set {
                this._contentUrl = value;
            }
        }
        
        /// <summary>The list of contributors for this scope.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("contributor")]
        public virtual System.Collections.Generic.IList<ItemScope> Contributor {
            get {
                return this._contributor;
            }
            set {
                this._contributor = value;
            }
        }
        
        /// <summary>The date this scope was created.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("dateCreated")]
        public virtual string DateCreated {
            get {
                return this._dateCreated;
            }
            set {
                this._dateCreated = value;
            }
        }
        
        /// <summary>The date this scope was last modified.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("dateModified")]
        public virtual string DateModified {
            get {
                return this._dateModified;
            }
            set {
                this._dateModified = value;
            }
        }
        
        /// <summary>The initial date this scope was published.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("datePublished")]
        public virtual string DatePublished {
            get {
                return this._datePublished;
            }
            set {
                this._datePublished = value;
            }
        }
        
        /// <summary>The string describing the content of this scope.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("description")]
        public virtual string Description {
            get {
                return this._description;
            }
            set {
                this._description = value;
            }
        }
        
        /// <summary>The duration of the item (movie, audio recording, event, etc.) in ISO 8601 date format.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("duration")]
        public virtual string Duration {
            get {
                return this._duration;
            }
            set {
                this._duration = value;
            }
        }
        
        /// <summary>A URL pointing to a player for a specific video. In general, this is the information in the src element of an embed tag and should not be the same as the content of the loc tag.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("embedUrl")]
        public virtual string EmbedUrl {
            get {
                return this._embedUrl;
            }
            set {
                this._embedUrl = value;
            }
        }
        
        /// <summary>The end date and time of the event (in ISO 8601 date format).</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("endDate")]
        public virtual string EndDate {
            get {
                return this._endDate;
            }
            set {
                this._endDate = value;
            }
        }
        
        /// <summary>Family name. In the U.S., the last name of an Person. This can be used along with givenName instead of the Name property.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("familyName")]
        public virtual string FamilyName {
            get {
                return this._familyName;
            }
            set {
                this._familyName = value;
            }
        }
        
        /// <summary>Gender of the person.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("gender")]
        public virtual string Gender {
            get {
                return this._gender;
            }
            set {
                this._gender = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("geo")]
        public virtual ItemScope Geo {
            get {
                return this._geo;
            }
            set {
                this._geo = value;
            }
        }
        
        /// <summary>Given name. In the U.S., the first name of a Person. This can be used along with familyName instead of the Name property.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("givenName")]
        public virtual string GivenName {
            get {
                return this._givenName;
            }
            set {
                this._givenName = value;
            }
        }
        
        /// <summary>The height of the media object.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("height")]
        public virtual string Height {
            get {
                return this._height;
            }
            set {
                this._height = value;
            }
        }
        
        /// <summary>The id for this item scope.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("id")]
        public virtual string Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        /// <summary>A url to the image for this scope.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("image")]
        public virtual string Image {
            get {
                return this._image;
            }
            set {
                this._image = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("inAlbum")]
        public virtual ItemScope InAlbum {
            get {
                return this._inAlbum;
            }
            set {
                this._inAlbum = value;
            }
        }
        
        /// <summary>Identifies this resource as an itemScope.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this._kind;
            }
            set {
                this._kind = value;
            }
        }
        
        /// <summary>Latitude.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("latitude")]
        public virtual System.Nullable<double> Latitude {
            get {
                return this._latitude;
            }
            set {
                this._latitude = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("location")]
        public virtual ItemScope Location {
            get {
                return this._location;
            }
            set {
                this._location = value;
            }
        }
        
        /// <summary>Longitude.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("longitude")]
        public virtual System.Nullable<double> Longitude {
            get {
                return this._longitude;
            }
            set {
                this._longitude = value;
            }
        }
        
        /// <summary>The name of this scope.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("name")]
        public virtual string Name {
            get {
                return this._name;
            }
            set {
                this._name = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("partOfTVSeries")]
        public virtual ItemScope PartOfTVSeries {
            get {
                return this._partOfTVSeries;
            }
            set {
                this._partOfTVSeries = value;
            }
        }
        
        /// <summary>The main performer or performers of the eventâ€”for example, a presenter, musician, or actor.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("performers")]
        public virtual System.Collections.Generic.IList<ItemScope> Performers {
            get {
                return this._performers;
            }
            set {
                this._performers = value;
            }
        }
        
        /// <summary>Player type requiredâ€”for example, Flash or Silverlight.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("playerType")]
        public virtual string PlayerType {
            get {
                return this._playerType;
            }
            set {
                this._playerType = value;
            }
        }
        
        /// <summary>Post office box number.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("postOfficeBoxNumber")]
        public virtual string PostOfficeBoxNumber {
            get {
                return this._postOfficeBoxNumber;
            }
            set {
                this._postOfficeBoxNumber = value;
            }
        }
        
        /// <summary>Postal code.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("postalCode")]
        public virtual string PostalCode {
            get {
                return this._postalCode;
            }
            set {
                this._postalCode = value;
            }
        }
        
        /// <summary>Rating value.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("ratingValue")]
        public virtual string RatingValue {
            get {
                return this._ratingValue;
            }
            set {
                this._ratingValue = value;
            }
        }
        
        /// <summary>Review rating.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("reviewRating")]
        public virtual System.Collections.Generic.IList<ItemScope> ReviewRating {
            get {
                return this._reviewRating;
            }
            set {
                this._reviewRating = value;
            }
        }
        
        /// <summary>The start date and time of the event (in ISO 8601 date format).</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("startDate")]
        public virtual string StartDate {
            get {
                return this._startDate;
            }
            set {
                this._startDate = value;
            }
        }
        
        /// <summary>Street address.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("streetAddress")]
        public virtual string StreetAddress {
            get {
                return this._streetAddress;
            }
            set {
                this._streetAddress = value;
            }
        }
        
        /// <summary>Comment text, review text, etc.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("text")]
        public virtual string Text {
            get {
                return this._text;
            }
            set {
                this._text = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("thumbnail")]
        public virtual ItemScope Thumbnail {
            get {
                return this._thumbnail;
            }
            set {
                this._thumbnail = value;
            }
        }
        
        /// <summary>A url to a thumbnail image for this scope.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("thumbnailUrl")]
        public virtual string ThumbnailUrl {
            get {
                return this._thumbnailUrl;
            }
            set {
                this._thumbnailUrl = value;
            }
        }
        
        /// <summary>The exchange traded instrument associated with a Corporation object. The tickerSymbol is expressed as an exchange and an instrument name separated by a space character. For the exchange component of the tickerSymbol attribute, we reccommend using the controlled vocaulary of Market Identifier Codes (MIC) specified in ISO15022.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("tickerSymbol")]
        public virtual string TickerSymbol {
            get {
                return this._tickerSymbol;
            }
            set {
                this._tickerSymbol = value;
            }
        }
        
        /// <summary>The item type.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("type")]
        public virtual string Type {
            get {
                return this._type;
            }
            set {
                this._type = value;
            }
        }
        
        /// <summary>A url for this scope.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("url")]
        public virtual string Url {
            get {
                return this._url;
            }
            set {
                this._url = value;
            }
        }
        
        /// <summary>The width of the media object.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("width")]
        public virtual string Width {
            get {
                return this._width;
            }
            set {
                this._width = value;
            }
        }
        
        /// <summary>Worst possible rating value.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("worstRating")]
        public virtual string WorstRating {
            get {
                return this._worstRating;
            }
            set {
                this._worstRating = value;
            }
        }
    }
    
    public class Moment : Google.Apis.Requests.IDirectResponseSchema {
        
        private string _kind;
        
        private ItemScope _result;
        
        private string _startDate;
        
        private ItemScope _target;
        
        private string _type;
        
        private Moment.VerbData _verb;
        
        private Google.Apis.Requests.RequestError _Error;
        
        private string _ETag;
        
        /// <summary>Identifies this resource as a moment.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this._kind;
            }
            set {
                this._kind = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("result")]
        public virtual ItemScope Result {
            get {
                return this._result;
            }
            set {
                this._result = value;
            }
        }
        
        /// <summary>Timestamp of the action (when it occured) in RFC3339 format.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("startDate")]
        public virtual string StartDate {
            get {
                return this._startDate;
            }
            set {
                this._startDate = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("target")]
        public virtual ItemScope Target {
            get {
                return this._target;
            }
            set {
                this._target = value;
            }
        }
        
        /// <summary>The schema.org activity type</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("type")]
        public virtual string Type {
            get {
                return this._type;
            }
            set {
                this._type = value;
            }
        }
        
        /// <summary>The action the user performed</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("verb")]
        public virtual Moment.VerbData Verb {
            get {
                return this._verb;
            }
            set {
                this._verb = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("error")]
        public virtual Google.Apis.Requests.RequestError Error {
            get {
                return this._Error;
            }
            set {
                this._Error = value;
            }
        }
        
        public virtual string ETag {
            get {
                return this._ETag;
            }
            set {
                this._ETag = value;
            }
        }
        
        /// <summary>The action the user performed</summary>
        public class VerbData {
            
            private string _url;
            
            /// <summary>Url name of the verb</summary>
            [Newtonsoft.Json.JsonPropertyAttribute("url")]
            public virtual string Url {
                get {
                    return this._url;
                }
                set {
                    this._url = value;
                }
            }
        }
    }
}
namespace Google.Apis.Plus.v1moments {
    using System;
    using System.IO;
    using System.Collections.Generic;
    using Google.Apis;
    using Google.Apis.Discovery;
    
    
    public partial class PlusService : Google.Apis.Discovery.IRequestProvider {
        
        private Google.Apis.Discovery.IService _service;
        
        private Google.Apis.Authentication.IAuthenticator _authenticator;
        
        private const string DiscoveryDocument = "{\"kind\":\"discovery#restDescription\",\"discoveryVersion\":\"v1\",\"id\":\"plus:v1moments\"" +
            ",\"name\":\"plus\",\"version\":\"v1moments\",\"revision\":\"20120525\",\"title\":\"Google+ API\"" +
            ",\"description\":\"The Google+ API enables developers to build on top of the Google" +
            "+ platform.\",\"icons\":{\"x16\":\"http://www.google.com/images/icons/product/gplus-16" +
            ".png\",\"x32\":\"http://www.google.com/images/icons/product/gplus-32.png\"},\"document" +
            "ationLink\":\"http://developers.google.com/+/api/\",\"labels\":[\"limited_availability" +
            "\"],\"protocol\":\"rest\",\"baseUrl\":\"https://www.googleapis.com/plus/v1moments/people" +
            "/\",\"basePath\":\"/plus/v1moments/people/\",\"rootUrl\":\"https://www.googleapis.com/\"," +
            "\"servicePath\":\"plus/v1moments/people/\",\"batchPath\":\"batch\",\"parameters\":{\"alt\":{" +
            "\"type\":\"string\",\"description\":\"Data format for the response.\",\"default\":\"json\",\"" +
            "enum\":[\"json\"],\"enumDescriptions\":[\"Responses with Content-Type of application/j" +
            "son\"],\"location\":\"query\"},\"fields\":{\"type\":\"string\",\"description\":\"Selector spec" +
            "ifying which fields to include in a partial response.\",\"location\":\"query\"},\"key\"" +
            ":{\"type\":\"string\",\"description\":\"API key. Your API key identifies your project a" +
            "nd provides you with API access, quota, and reports. Required unless you provide" +
            " an OAuth 2.0 token.\",\"location\":\"query\"},\"oauth_token\":{\"type\":\"string\",\"descri" +
            "ption\":\"OAuth 2.0 token for the current user.\",\"location\":\"query\"},\"prettyPrint\"" +
            ":{\"type\":\"boolean\",\"description\":\"Returns response with indentations and line br" +
            "eaks.\",\"default\":\"true\",\"location\":\"query\"},\"quotaUser\":{\"type\":\"string\",\"descri" +
            "ption\":\"Available to use for quota purposes for server-side applications. Can be" +
            " any arbitrary string assigned to a user, but should not exceed 40 characters. O" +
            "verrides userIp if both are provided.\",\"location\":\"query\"},\"userIp\":{\"type\":\"str" +
            "ing\",\"description\":\"IP address of the site where the request originates. Use thi" +
            "s if you want to enforce per-user limits.\",\"location\":\"query\"}},\"auth\":{\"oauth2\"" +
            ":{\"scopes\":{\"https://www.googleapis.com/auth/plus.moments.write\":{\"description\":" +
            "\"View and manage user activity information in Google+\"}}}},\"schemas\":{\"ItemScope" +
            "\":{\"id\":\"ItemScope\",\"type\":\"object\",\"properties\":{\"about\":{\"$ref\":\"ItemScope\",\"d" +
            "escription\":\"The subject matter of the content.\"},\"additionalName\":{\"type\":\"arra" +
            "y\",\"description\":\"An additional name for a Person, can be used for a middle name" +
            ".\",\"items\":{\"type\":\"string\"}},\"address\":{\"$ref\":\"ItemScope\",\"description\":\"Posta" +
            "l address.\"},\"addressCountry\":{\"type\":\"string\",\"description\":\"Address country.\"}" +
            ",\"addressLocality\":{\"type\":\"string\",\"description\":\"Address locality.\"},\"addressR" +
            "egion\":{\"type\":\"string\",\"description\":\"Address region.\"},\"associated_media\":{\"ty" +
            "pe\":\"array\",\"description\":\"The encoding.\",\"items\":{\"$ref\":\"ItemScope\"}},\"attende" +
            "eCount\":{\"type\":\"integer\",\"description\":\"Number of attendees.\",\"format\":\"int32\"}" +
            ",\"attendees\":{\"type\":\"array\",\"description\":\"A person attending the event.\",\"item" +
            "s\":{\"$ref\":\"ItemScope\"}},\"audio\":{\"$ref\":\"ItemScope\",\"description\":\"From http://" +
            "schema.org/MusicRecording, the audio file.\"},\"author\":{\"type\":\"array\",\"descripti" +
            "on\":\"The person who created this scope.\",\"items\":{\"$ref\":\"ItemScope\"}},\"bestRati" +
            "ng\":{\"type\":\"string\",\"description\":\"Best possible rating value.\"},\"birthDate\":{\"" +
            "type\":\"string\",\"description\":\"Date of birth.\"},\"byArtist\":{\"$ref\":\"ItemScope\",\"d" +
            "escription\":\"From http://schema.org/MusicRecording, the artist that performed th" +
            "is recording.\"},\"caption\":{\"type\":\"string\",\"description\":\"The caption for this o" +
            "bject.\"},\"contentSize\":{\"type\":\"string\",\"description\":\"File size in (mega/kilo) " +
            "bytes.\"},\"contentUrl\":{\"type\":\"string\",\"description\":\"Actual bytes of the media " +
            "object, for example the image file or video file.\"},\"contributor\":{\"type\":\"array" +
            "\",\"description\":\"The list of contributors for this scope.\",\"items\":{\"$ref\":\"Item" +
            "Scope\"}},\"dateCreated\":{\"type\":\"string\",\"description\":\"The date this scope was c" +
            "reated.\"},\"dateModified\":{\"type\":\"string\",\"description\":\"The date this scope was" +
            " last modified.\"},\"datePublished\":{\"type\":\"string\",\"description\":\"The initial da" +
            "te this scope was published.\"},\"description\":{\"type\":\"string\",\"description\":\"The" +
            " string describing the content of this scope.\"},\"duration\":{\"type\":\"string\",\"des" +
            "cription\":\"The duration of the item (movie, audio recording, event, etc.) in ISO" +
            " 8601 date format.\"},\"embedUrl\":{\"type\":\"string\",\"description\":\"A URL pointing t" +
            "o a player for a specific video. In general, this is the information in the src " +
            "element of an embed tag and should not be the same as the content of the loc tag" +
            ".\"},\"endDate\":{\"type\":\"string\",\"description\":\"The end date and time of the event" +
            " (in ISO 8601 date format).\"},\"familyName\":{\"type\":\"string\",\"description\":\"Famil" +
            "y name. In the U.S., the last name of an Person. This can be used along with giv" +
            "enName instead of the Name property.\"},\"gender\":{\"type\":\"string\",\"description\":\"" +
            "Gender of the person.\"},\"geo\":{\"$ref\":\"ItemScope\",\"description\":\"Geo coordinates" +
            ".\"},\"givenName\":{\"type\":\"string\",\"description\":\"Given name. In the U.S., the fir" +
            "st name of a Person. This can be used along with familyName instead of the Name " +
            "property.\"},\"height\":{\"type\":\"string\",\"description\":\"The height of the media obj" +
            "ect.\"},\"id\":{\"type\":\"string\",\"description\":\"The id for this item scope.\"},\"image" +
            "\":{\"type\":\"string\",\"description\":\"A url to the image for this scope.\"},\"inAlbum\"" +
            ":{\"$ref\":\"ItemScope\",\"description\":\"From http://schema.org/MusicRecording, which" +
            " album a song is in.\"},\"kind\":{\"type\":\"string\",\"description\":\"Identifies this re" +
            "source as an itemScope.\",\"default\":\"plus#itemScope\"},\"latitude\":{\"type\":\"number\"" +
            ",\"description\":\"Latitude.\",\"format\":\"double\"},\"location\":{\"$ref\":\"ItemScope\",\"de" +
            "scription\":\"The location of the event or organization.\"},\"longitude\":{\"type\":\"nu" +
            "mber\",\"description\":\"Longitude.\",\"format\":\"double\"},\"name\":{\"type\":\"string\",\"des" +
            "cription\":\"The name of this scope.\"},\"partOfTVSeries\":{\"$ref\":\"ItemScope\",\"descr" +
            "iption\":\"Property of http://schema.org/TVEpisode indicating which series the epi" +
            "sode belongs to.\"},\"performers\":{\"type\":\"array\",\"description\":\"The main performe" +
            "r or performers of the eventâ€”for example, a presenter, musician, or actor.\",\"i" +
            "tems\":{\"$ref\":\"ItemScope\"}},\"playerType\":{\"type\":\"string\",\"description\":\"Player " +
            "type requiredâ€”for example, Flash or Silverlight.\"},\"postOfficeBoxNumber\":{\"typ" +
            "e\":\"string\",\"description\":\"Post office box number.\"},\"postalCode\":{\"type\":\"strin" +
            "g\",\"description\":\"Postal code.\"},\"ratingValue\":{\"type\":\"string\",\"description\":\"R" +
            "ating value.\"},\"reviewRating\":{\"type\":\"array\",\"description\":\"Review rating.\",\"it" +
            "ems\":{\"$ref\":\"ItemScope\"}},\"startDate\":{\"type\":\"string\",\"description\":\"The start" +
            " date and time of the event (in ISO 8601 date format).\"},\"streetAddress\":{\"type\"" +
            ":\"string\",\"description\":\"Street address.\"},\"text\":{\"type\":\"string\",\"description\"" +
            ":\"Comment text, review text, etc.\"},\"thumbnail\":{\"$ref\":\"ItemScope\",\"description" +
            "\":\"Thumbnail image for an image or video.\"},\"thumbnailUrl\":{\"type\":\"string\",\"des" +
            "cription\":\"A url to a thumbnail image for this scope.\"},\"tickerSymbol\":{\"type\":\"" +
            "string\",\"description\":\"The exchange traded instrument associated with a Corporat" +
            "ion object. The tickerSymbol is expressed as an exchange and an instrument name " +
            "separated by a space character. For the exchange component of the tickerSymbol a" +
            "ttribute, we reccommend using the controlled vocaulary of Market Identifier Code" +
            "s (MIC) specified in ISO15022.\"},\"type\":{\"type\":\"string\",\"description\":\"The item" +
            " type.\"},\"url\":{\"type\":\"string\",\"description\":\"A url for this scope.\"},\"width\":{" +
            "\"type\":\"string\",\"description\":\"The width of the media object.\"},\"worstRating\":{\"" +
            "type\":\"string\",\"description\":\"Worst possible rating value.\"}}},\"Moment\":{\"id\":\"M" +
            "oment\",\"type\":\"object\",\"properties\":{\"kind\":{\"type\":\"string\",\"description\":\"Iden" +
            "tifies this resource as a moment.\",\"default\":\"plus#moment\"},\"result\":{\"$ref\":\"It" +
            "emScope\",\"description\":\"The object generated by performing the action on the ite" +
            "m\"},\"startDate\":{\"type\":\"string\",\"description\":\"Timestamp of the action (when it" +
            " occured) in RFC3339 format.\",\"format\":\"date-time\"},\"target\":{\"$ref\":\"ItemScope\"" +
            ",\"description\":\"The object on which the action was performed\"},\"type\":{\"type\":\"s" +
            "tring\",\"description\":\"The schema.org activity type\"},\"verb\":{\"type\":\"object\",\"de" +
            "scription\":\"The action the user performed\",\"properties\":{\"url\":{\"type\":\"string\"," +
            "\"description\":\"Url name of the verb\"}}}}}},\"resources\":{\"moments\":{\"methods\":{\"i" +
            "nsert\":{\"id\":\"plus.moments.insert\",\"path\":\"{userId}/moments/{collection}\",\"httpM" +
            "ethod\":\"POST\",\"description\":\"Record a user activity (e.g Bill watched a video on" +
            " Youtube)\",\"parameters\":{\"collection\":{\"type\":\"string\",\"description\":\"The collec" +
            "tion to which to write moments.\",\"required\":true,\"enum\":[\"vault\"],\"enumDescripti" +
            "ons\":[\"The default collection for writing new moments.\"],\"location\":\"path\"},\"deb" +
            "ug\":{\"type\":\"boolean\",\"description\":\"Return the moment as written. Should be use" +
            "d only for debugging.\",\"location\":\"query\"},\"userId\":{\"type\":\"string\",\"descriptio" +
            "n\":\"The ID of the user to get activities for. The special value \\\"me\\\" can be us" +
            "ed to indicate the authenticated user.\",\"required\":true,\"pattern\":\"me\",\"location" +
            "\":\"path\"}},\"parameterOrder\":[\"userId\",\"collection\"],\"request\":{\"$ref\":\"Moment\"}," +
            "\"response\":{\"$ref\":\"Moment\"},\"scopes\":[\"https://www.googleapis.com/auth/plus.mom" +
            "ents.write\"]}}}}}";
        
        public const string Version = "v1moments";
        
        public static Google.Apis.Discovery.DiscoveryVersion DiscoveryVersionUsed = Google.Apis.Discovery.DiscoveryVersion.Version_1_0;
        
        private string _Key;
        
        protected PlusService(Google.Apis.Discovery.IService _service, Google.Apis.Authentication.IAuthenticator _authenticator) {
            this._service = _service;
            this._authenticator = _authenticator;
            this._moments = new MomentsResource(this, _authenticator);
        }
        
        public PlusService() : 
                this(Google.Apis.Authentication.NullAuthenticator.Instance) {
        }
        
        public PlusService(Google.Apis.Authentication.IAuthenticator _authenticator) : 
                this(new Google.Apis.Discovery.DiscoveryService(new Google.Apis.Discovery.StringDiscoveryDevice(DiscoveryDocument)).GetService(PlusService.DiscoveryVersionUsed, new Google.Apis.Discovery.FactoryParameters(new System.Uri("https://www.googleapis.com/plus/v1moments/people/"))), _authenticator) {
        }
        
        public Google.Apis.Authentication.IAuthenticator Authenticator {
            get {
                return this._authenticator;
            }
        }
        
        public virtual string Name {
            get {
                return "plus";
            }
        }
        
        public virtual string BaseUri {
            get {
                return "https://www.googleapis.com/plus/v1moments/people/";
            }
        }
        
        /// <summary>Sets the API-Key (or DeveloperKey) which this service uses for all requests</summary>
        public virtual string Key {
            get {
                return this._Key;
            }
            set {
                this._Key = value;
            }
        }
        
        public virtual Google.Apis.Requests.IRequest CreateRequest(string resource, string method) {
            Google.Apis.Requests.IRequest request = this._service.CreateRequest(resource, method);
            if ((string.IsNullOrEmpty(Key) == false)) {
                request = request.WithKey(this.Key);
            }
            return request.WithAuthentication(_authenticator);
        }
        
        public virtual void RegisterSerializer(Google.Apis.ISerializer serializer) {
            _service.Serializer = serializer;
        }
        
        public virtual string SerializeObject(object obj) {
            return _service.SerializeRequest(obj);
        }
        
        public virtual T DeserializeResponse<T>(Google.Apis.Requests.IResponse response)
         {
            return _service.DeserializeResponse<T>(response);
        }
        
        /// <summary>A list of all OAuth2.0 scopes. Each of these scopes relates to a permission or group of permissions that different methods of this API may need.</summary>
        public enum Scopes {
            
            /// <summary>View and manage user activity information in Google+</summary>
            [Google.Apis.Util.StringValueAttribute("https://www.googleapis.com/auth/plus.moments.write")]
            PlusMomentsWrite,
        }
    }
    
    public class MomentsResource {
        
        private PlusService service;
        
        private Google.Apis.Authentication.IAuthenticator _authenticator;
        
        private const string Resource = "moments";
        
        public MomentsResource(PlusService service, Google.Apis.Authentication.IAuthenticator _authenticator) {
            this.service = service;
            this._authenticator = _authenticator;
        }
        
        /// <summary>Record a user activity (e.g Bill watched a video on Youtube)</summary>
        /// <param name="userId">Required - Must match pattern me - The ID of the user to get activities for. The special value &quot;me&quot; can be used to indicate the authenticated user.</param>
        /// <param name="collection">Required - Must be one of the following values [vault] - The collection to which to write moments.</param>
        public virtual InsertRequest Insert(Google.Apis.Plus.v1moments.Data.Moment body, string userId, Collection collection) {
            return new InsertRequest(service, body, userId, collection);
        }
        
        /// <summary>The collection to which to write moments.</summary>
        [System.ComponentModel.TypeConverterAttribute(typeof(Google.Apis.Util.EnumStringValueTypeConverter))]
        public enum Collection {
            
            /// <summary>The default collection for writing new moments.</summary>
            [Google.Apis.Util.StringValueAttribute("vault")]
            Vault,
        }
        
        public class InsertRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Plus.v1moments.Data.Moment> {
            
            private string _oauth_token;
            
            private System.Nullable<bool> _prettyPrint;
            
            private string _quotaUser;
            
            private Collection _collection;
            
            private System.Nullable<bool> _debug;
            
            private string _userId;
            
            private Google.Apis.Plus.v1moments.Data.Moment _Body;
            
            public InsertRequest(Google.Apis.Discovery.IRequestProvider service, Google.Apis.Plus.v1moments.Data.Moment body, string userId, Collection collection) : 
                    base(service) {
                this.Body = body;
                this._userId = userId;
                this._collection = collection;
            }
            
            /// <summary>OAuth 2.0 token for the current user.</summary>
            [Google.Apis.Util.RequestParameterAttribute("oauth_token", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string Oauth_token {
                get {
                    return this._oauth_token;
                }
                set {
                    this._oauth_token = value;
                }
            }
            
            /// <summary>Returns response with indentations and line breaks.</summary>
            [Google.Apis.Util.RequestParameterAttribute("prettyPrint", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> PrettyPrint {
                get {
                    return this._prettyPrint;
                }
                set {
                    this._prettyPrint = value;
                }
            }
            
            /// <summary>Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</summary>
            [Google.Apis.Util.RequestParameterAttribute("quotaUser", Google.Apis.Util.RequestParameterType.Query)]
            public virtual string QuotaUser {
                get {
                    return this._quotaUser;
                }
                set {
                    this._quotaUser = value;
                }
            }
            
            /// <summary>The collection to which to write moments.</summary>
            [Google.Apis.Util.RequestParameterAttribute("collection", Google.Apis.Util.RequestParameterType.Path)]
            public virtual Collection Collection {
                get {
                    return this._collection;
                }
            }
            
            /// <summary>Return the moment as written. Should be used only for debugging.</summary>
            [Google.Apis.Util.RequestParameterAttribute("debug", Google.Apis.Util.RequestParameterType.Query)]
            public virtual System.Nullable<bool> Debug {
                get {
                    return this._debug;
                }
                set {
                    this._debug = value;
                }
            }
            
            /// <summary>The ID of the user to get activities for. The special value "me" can be used to indicate the authenticated user.</summary>
            [Google.Apis.Util.RequestParameterAttribute("userId", Google.Apis.Util.RequestParameterType.Path)]
            public virtual string UserId {
                get {
                    return this._userId;
                }
            }
            
            /// <summary>Gets/Sets the Body of this Request.</summary>
            public virtual Google.Apis.Plus.v1moments.Data.Moment Body {
                get {
                    return this._Body;
                }
                set {
                    this._Body = value;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "moments";
                }
            }
            
            protected override string MethodName {
                get {
                    return "insert";
                }
            }
            
            protected override object GetBody() {
                return this.Body;
            }
        }
    }
    
    public partial class PlusService {
        
        private const string Resource = "";
        
        private MomentsResource _moments;
        
        private Google.Apis.Discovery.IRequestProvider service {
            get {
                return this;
            }
        }
        
        public virtual MomentsResource Moments {
            get {
                return this._moments;
            }
        }
    }
}
