//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Google.Apis.Tasks.v1.Data {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    
    
    public class Task : Google.Apis.Requests.IDirectResponseSchema {
        
        private string completed;
        
        private System.Nullable<bool> deleted;
        
        private string due;
        
        private string etag;
        
        private System.Nullable<bool> hidden;
        
        private string id;
        
        private string kind;
        
        private string notes;
        
        private string parent;
        
        private string position;
        
        private string selfLink;
        
        private string status;
        
        private string title;
        
        private string updated;
        
        private Google.Apis.Requests.RequestError error;
        
        /// <summary>Completion date of the task (as a RFC 3339 timestamp). This field is omitted if the task has not been completed.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("completed")]
        public virtual string Completed {
            get {
                return this.completed;
            }
            set {
                this.completed = value;
            }
        }
        
        /// <summary>Flag indicating whether the task has been deleted. The default if False.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("deleted")]
        public virtual System.Nullable<bool> Deleted {
            get {
                return this.deleted;
            }
            set {
                this.deleted = value;
            }
        }
        
        /// <summary>Due date of the task (as a RFC 3339 timestamp). Optional.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("due")]
        public virtual string Due {
            get {
                return this.due;
            }
            set {
                this.due = value;
            }
        }
        
        /// <summary>ETag of the resource.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("etag")]
        public virtual string ETag {
            get {
                return this.etag;
            }
            set {
                this.etag = value;
            }
        }
        
        /// <summary>Flag indicating whether the task is hidden. This is the case if the task had been marked completed when the task list was last cleared. The default is False. This field is read-only.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("hidden")]
        public virtual System.Nullable<bool> Hidden {
            get {
                return this.hidden;
            }
            set {
                this.hidden = value;
            }
        }
        
        /// <summary>Task identifier.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("id")]
        public virtual string Id {
            get {
                return this.id;
            }
            set {
                this.id = value;
            }
        }
        
        /// <summary>Type of the resource. This is always &quot;tasks#task&quot;.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this.kind;
            }
            set {
                this.kind = value;
            }
        }
        
        /// <summary>Notes describing the task. Optional.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("notes")]
        public virtual string Notes {
            get {
                return this.notes;
            }
            set {
                this.notes = value;
            }
        }
        
        /// <summary>Parent task identifier. This field is omitted if it is a top-level task. This field is read-only. Use the &quot;move&quot; method to move the task under a different parent or to the top level.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("parent")]
        public virtual string Parent {
            get {
                return this.parent;
            }
            set {
                this.parent = value;
            }
        }
        
        /// <summary>String indicating the position of the task among its sibling tasks under the same parent task or at the top level. If this string is greater than another task&apos;s corresponding position string according to lexicographical ordering, the task is positioned after the other task under the same parent task (or at the top level). This field is read-only. Use the &quot;move&quot; method to move the task to another position.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("position")]
        public virtual string Position {
            get {
                return this.position;
            }
            set {
                this.position = value;
            }
        }
        
        /// <summary>URL pointing to this task. Used to retrieve, update, or delete this task.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("selfLink")]
        public virtual string SelfLink {
            get {
                return this.selfLink;
            }
            set {
                this.selfLink = value;
            }
        }
        
        /// <summary>Status of the task. This is either &quot;needsAction&quot; or &quot;completed&quot;.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("status")]
        public virtual string Status {
            get {
                return this.status;
            }
            set {
                this.status = value;
            }
        }
        
        /// <summary>Title of the task.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("title")]
        public virtual string Title {
            get {
                return this.title;
            }
            set {
                this.title = value;
            }
        }
        
        /// <summary>Last modification time of the task (as a RFC 3339 timestamp).</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("updated")]
        public virtual string Updated {
            get {
                return this.updated;
            }
            set {
                this.updated = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("error")]
        public virtual Google.Apis.Requests.RequestError Error {
            get {
                return this.error;
            }
            set {
                this.error = value;
            }
        }
    }
    
    public class TaskList : Google.Apis.Requests.IDirectResponseSchema {
        
        private string etag;
        
        private string id;
        
        private string kind;
        
        private string selfLink;
        
        private string title;
        
        private Google.Apis.Requests.RequestError error;
        
        /// <summary>ETag of the resource.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("etag")]
        public virtual string ETag {
            get {
                return this.etag;
            }
            set {
                this.etag = value;
            }
        }
        
        /// <summary>Task list identifier.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("id")]
        public virtual string Id {
            get {
                return this.id;
            }
            set {
                this.id = value;
            }
        }
        
        /// <summary>Type of the resource. This is always &quot;tasks#taskList&quot;.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this.kind;
            }
            set {
                this.kind = value;
            }
        }
        
        /// <summary>URL pointing to this task list. Used to retrieve, update, or delete this task list.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("selfLink")]
        public virtual string SelfLink {
            get {
                return this.selfLink;
            }
            set {
                this.selfLink = value;
            }
        }
        
        /// <summary>Title of the task list.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("title")]
        public virtual string Title {
            get {
                return this.title;
            }
            set {
                this.title = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("error")]
        public virtual Google.Apis.Requests.RequestError Error {
            get {
                return this.error;
            }
            set {
                this.error = value;
            }
        }
    }
    
    public class TaskLists : Google.Apis.Requests.IDirectResponseSchema {
        
        private string etag;
        
        private IList<TaskList> items;
        
        private string kind;
        
        private string nextPageToken;
        
        private Google.Apis.Requests.RequestError error;
        
        /// <summary>ETag of the resource.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("etag")]
        public virtual string ETag {
            get {
                return this.etag;
            }
            set {
                this.etag = value;
            }
        }
        
        /// <summary>Collection of task lists.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("items")]
        public virtual IList<TaskList> Items {
            get {
                return this.items;
            }
            set {
                this.items = value;
            }
        }
        
        /// <summary>Type of the resource. This is always &quot;tasks#taskLists&quot;.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this.kind;
            }
            set {
                this.kind = value;
            }
        }
        
        /// <summary>Token that can be used to request the next page of this result.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("nextPageToken")]
        public virtual string NextPageToken {
            get {
                return this.nextPageToken;
            }
            set {
                this.nextPageToken = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("error")]
        public virtual Google.Apis.Requests.RequestError Error {
            get {
                return this.error;
            }
            set {
                this.error = value;
            }
        }
    }
    
    public class Tasks : Google.Apis.Requests.IDirectResponseSchema {
        
        private string etag;
        
        private IList<Task> items;
        
        private string kind;
        
        private string nextPageToken;
        
        private Google.Apis.Requests.RequestError error;
        
        /// <summary>ETag of the resource.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("etag")]
        public virtual string ETag {
            get {
                return this.etag;
            }
            set {
                this.etag = value;
            }
        }
        
        /// <summary>Collection of tasks.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("items")]
        public virtual IList<Task> Items {
            get {
                return this.items;
            }
            set {
                this.items = value;
            }
        }
        
        /// <summary>Type of the resource. This is always &quot;tasks#tasks&quot;.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind {
            get {
                return this.kind;
            }
            set {
                this.kind = value;
            }
        }
        
        /// <summary>Token used to access the next page of this result.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("nextPageToken")]
        public virtual string NextPageToken {
            get {
                return this.nextPageToken;
            }
            set {
                this.nextPageToken = value;
            }
        }
        
        [Newtonsoft.Json.JsonPropertyAttribute("error")]
        public virtual Google.Apis.Requests.RequestError Error {
            get {
                return this.error;
            }
            set {
                this.error = value;
            }
        }
    }
}
namespace Google.Apis.Tasks.v1 {
    using System;
    using System.IO;
    using System.Collections.Generic;
    using Google.Apis;
    using Google.Apis.Discovery;
    
    
    public partial class TasksService : Google.Apis.Discovery.IRequestProvider {
        
        private Google.Apis.Discovery.IService genericService;
        
        private Google.Apis.Authentication.IAuthenticator authenticator;
        
        private const string DiscoveryDocument = "{\"kind\":\"discovery#restDescription\",\"id\":\"tasks:v1\",\"name\":\"tasks\",\"version\":\"v1\"" +
            ",\"title\":\"Tasks API\",\"description\":\"Lets you manage your tasks and task lists.\"," +
            "\"icons\":{\"x16\":\"http://www.google.com/images/icons/product/tasks-16.png\",\"x32\":\"" +
            "http://www.google.com/images/icons/product/tasks-32.png\"},\"documentationLink\":\"h" +
            "ttp://code.google.com/apis/tasks/v1/using.html\",\"labels\":[\"labs\"],\"protocol\":\"re" +
            "st\",\"basePath\":\"/tasks/v1/\",\"parameters\":{\"alt\":{\"type\":\"string\",\"description\":\"" +
            "Data format for the response.\",\"default\":\"json\",\"enum\":[\"json\"],\"enumDescription" +
            "s\":[\"Responses with Content-Type of application/json\"],\"location\":\"query\"},\"fiel" +
            "ds\":{\"type\":\"string\",\"description\":\"Selector specifying which fields to include " +
            "in a partial response.\",\"location\":\"query\"},\"key\":{\"type\":\"string\",\"description\"" +
            ":\"API key. Your API key identifies your project and provides you with API access" +
            ", quota, and reports. Required unless you provide an OAuth 2.0 token.\",\"location" +
            "\":\"query\"},\"oauth_token\":{\"type\":\"string\",\"description\":\"OAuth 2.0 token for the" +
            " current user.\",\"location\":\"query\"},\"prettyPrint\":{\"type\":\"boolean\",\"description" +
            "\":\"Returns response with indentations and line breaks.\",\"default\":\"true\",\"locati" +
            "on\":\"query\"},\"userIp\":{\"type\":\"string\",\"description\":\"IP address of the site whe" +
            "re the request originates. Use this if you want to enforce per-user limits.\",\"lo" +
            "cation\":\"query\"}},\"auth\":{\"oauth2\":{\"scopes\":{\"https://www.googleapis.com/auth/t" +
            "asks\":{\"description\":\"Manage your tasks\"},\"https://www.googleapis.com/auth/tasks" +
            ".readonly\":{\"description\":\"View your tasks\"}}}},\"schemas\":{\"Task\":{\"id\":\"Task\",\"" +
            "type\":\"object\",\"properties\":{\"completed\":{\"type\":\"string\",\"description\":\"Complet" +
            "ion date of the task (as a RFC 3339 timestamp). This field is omitted if the tas" +
            "k has not been completed.\",\"format\":\"date-time\"},\"deleted\":{\"type\":\"boolean\",\"de" +
            "scription\":\"Flag indicating whether the task has been deleted. The default if Fa" +
            "lse.\"},\"due\":{\"type\":\"string\",\"description\":\"Due date of the task (as a RFC 3339" +
            " timestamp). Optional.\",\"format\":\"date-time\"},\"etag\":{\"type\":\"string\",\"descripti" +
            "on\":\"ETag of the resource.\"},\"hidden\":{\"type\":\"boolean\",\"description\":\"Flag indi" +
            "cating whether the task is hidden. This is the case if the task had been marked " +
            "completed when the task list was last cleared. The default is False. This field " +
            "is read-only.\"},\"id\":{\"type\":\"string\",\"description\":\"Task identifier.\"},\"kind\":{" +
            "\"type\":\"string\",\"description\":\"Type of the resource. This is always \\\"tasks#task" +
            "\\\".\",\"default\":\"tasks#task\"},\"notes\":{\"type\":\"string\",\"description\":\"Notes descr" +
            "ibing the task. Optional.\"},\"parent\":{\"type\":\"string\",\"description\":\"Parent task" +
            " identifier. This field is omitted if it is a top-level task. This field is read" +
            "-only. Use the \\\"move\\\" method to move the task under a different parent or to t" +
            "he top level.\"},\"position\":{\"type\":\"string\",\"description\":\"String indicating the" +
            " position of the task among its sibling tasks under the same parent task or at t" +
            "he top level. If this string is greater than another task\'s corresponding positi" +
            "on string according to lexicographical ordering, the task is positioned after th" +
            "e other task under the same parent task (or at the top level). This field is rea" +
            "d-only. Use the \\\"move\\\" method to move the task to another position.\"},\"selfLin" +
            "k\":{\"type\":\"string\",\"description\":\"URL pointing to this task. Used to retrieve, " +
            "update, or delete this task.\"},\"status\":{\"type\":\"string\",\"description\":\"Status o" +
            "f the task. This is either \\\"needsAction\\\" or \\\"completed\\\".\"},\"title\":{\"type\":\"" +
            "string\",\"description\":\"Title of the task.\"},\"updated\":{\"type\":\"string\",\"descript" +
            "ion\":\"Last modification time of the task (as a RFC 3339 timestamp).\",\"format\":\"d" +
            "ate-time\"}}},\"TaskList\":{\"id\":\"TaskList\",\"type\":\"object\",\"properties\":{\"etag\":{\"" +
            "type\":\"string\",\"description\":\"ETag of the resource.\"},\"id\":{\"type\":\"string\",\"des" +
            "cription\":\"Task list identifier.\"},\"kind\":{\"type\":\"string\",\"description\":\"Type o" +
            "f the resource. This is always \\\"tasks#taskList\\\".\",\"default\":\"tasks#taskList\"}," +
            "\"selfLink\":{\"type\":\"string\",\"description\":\"URL pointing to this task list. Used " +
            "to retrieve, update, or delete this task list.\"},\"title\":{\"type\":\"string\",\"descr" +
            "iption\":\"Title of the task list.\"}}},\"TaskLists\":{\"id\":\"TaskLists\",\"type\":\"objec" +
            "t\",\"properties\":{\"etag\":{\"type\":\"string\",\"description\":\"ETag of the resource.\"}," +
            "\"items\":{\"type\":\"array\",\"description\":\"Collection of task lists.\",\"items\":{\"$ref" +
            "\":\"TaskList\"}},\"kind\":{\"type\":\"string\",\"description\":\"Type of the resource. This" +
            " is always \\\"tasks#taskLists\\\".\",\"default\":\"tasks#taskLists\"},\"nextPageToken\":{\"" +
            "type\":\"string\",\"description\":\"Token that can be used to request the next page of" +
            " this result.\"}}},\"Tasks\":{\"id\":\"Tasks\",\"type\":\"object\",\"properties\":{\"etag\":{\"t" +
            "ype\":\"string\",\"description\":\"ETag of the resource.\"},\"items\":{\"type\":\"array\",\"de" +
            "scription\":\"Collection of tasks.\",\"items\":{\"$ref\":\"Task\"}},\"kind\":{\"type\":\"strin" +
            "g\",\"description\":\"Type of the resource. This is always \\\"tasks#tasks\\\".\",\"defaul" +
            "t\":\"tasks#tasks\"},\"nextPageToken\":{\"type\":\"string\",\"description\":\"Token used to " +
            "access the next page of this result.\"}}}},\"resources\":{\"tasklists\":{\"methods\":{\"" +
            "delete\":{\"id\":\"tasks.tasklists.delete\",\"path\":\"users/@me/lists/{tasklist}\",\"http" +
            "Method\":\"DELETE\",\"description\":\"Deletes the authenticated user\'s specified task " +
            "list.\",\"parameters\":{\"tasklist\":{\"type\":\"string\",\"description\":\"Task list identi" +
            "fier.\",\"required\":true,\"location\":\"path\"}},\"parameterOrder\":[\"tasklist\"],\"scopes" +
            "\":[\"https://www.googleapis.com/auth/tasks\"]},\"get\":{\"id\":\"tasks.tasklists.get\",\"" +
            "path\":\"users/@me/lists/{tasklist}\",\"httpMethod\":\"GET\",\"description\":\"Returns the" +
            " authenticated user\'s specified task list.\",\"parameters\":{\"tasklist\":{\"type\":\"st" +
            "ring\",\"description\":\"Task list identifier.\",\"required\":true,\"location\":\"path\"}}," +
            "\"parameterOrder\":[\"tasklist\"],\"response\":{\"$ref\":\"TaskList\"},\"scopes\":[\"https://" +
            "www.googleapis.com/auth/tasks\",\"https://www.googleapis.com/auth/tasks.readonly\"]" +
            "},\"insert\":{\"id\":\"tasks.tasklists.insert\",\"path\":\"users/@me/lists\",\"httpMethod\":" +
            "\"POST\",\"description\":\"Creates a new task list and adds it to the authenticated u" +
            "ser\'s task lists.\",\"request\":{\"$ref\":\"TaskList\"},\"response\":{\"$ref\":\"TaskList\"}," +
            "\"scopes\":[\"https://www.googleapis.com/auth/tasks\"]},\"list\":{\"id\":\"tasks.tasklist" +
            "s.list\",\"path\":\"users/@me/lists\",\"httpMethod\":\"GET\",\"description\":\"Returns all t" +
            "he authenticated user\'s task lists.\",\"parameters\":{\"maxResults\":{\"type\":\"string\"" +
            ",\"description\":\"Maximum number of task lists returned on one page. Optional. The" +
            " default is 100.\",\"format\":\"int64\",\"location\":\"query\"},\"pageToken\":{\"type\":\"stri" +
            "ng\",\"description\":\"Token specifying the result page to return. Optional.\",\"locat" +
            "ion\":\"query\"}},\"response\":{\"$ref\":\"TaskLists\"},\"scopes\":[\"https://www.googleapis" +
            ".com/auth/tasks\",\"https://www.googleapis.com/auth/tasks.readonly\"]},\"patch\":{\"id" +
            "\":\"tasks.tasklists.patch\",\"path\":\"users/@me/lists/{tasklist}\",\"httpMethod\":\"PATC" +
            "H\",\"description\":\"Updates the authenticated user\'s specified task list. This met" +
            "hod supports patch semantics.\",\"parameters\":{\"tasklist\":{\"type\":\"string\",\"descri" +
            "ption\":\"Task list identifier.\",\"required\":true,\"location\":\"path\"}},\"parameterOrd" +
            "er\":[\"tasklist\"],\"request\":{\"$ref\":\"TaskList\"},\"response\":{\"$ref\":\"TaskList\"},\"s" +
            "copes\":[\"https://www.googleapis.com/auth/tasks\"]},\"update\":{\"id\":\"tasks.tasklist" +
            "s.update\",\"path\":\"users/@me/lists/{tasklist}\",\"httpMethod\":\"PUT\",\"description\":\"" +
            "Updates the authenticated user\'s specified task list.\",\"parameters\":{\"tasklist\":" +
            "{\"type\":\"string\",\"description\":\"Task list identifier.\",\"required\":true,\"location" +
            "\":\"path\"}},\"parameterOrder\":[\"tasklist\"],\"request\":{\"$ref\":\"TaskList\"},\"response" +
            "\":{\"$ref\":\"TaskList\"},\"scopes\":[\"https://www.googleapis.com/auth/tasks\"]}}},\"tas" +
            "ks\":{\"methods\":{\"clear\":{\"id\":\"tasks.tasks.clear\",\"path\":\"lists/{tasklist}/clear" +
            "\",\"httpMethod\":\"POST\",\"description\":\"Clears all completed tasks from the specifi" +
            "ed task list. The affected tasks will be marked as \'hidden\' and no longer be ret" +
            "urned by default when retrieving all tasks for a task list.\",\"parameters\":{\"task" +
            "list\":{\"type\":\"string\",\"description\":\"Task list identifier.\",\"required\":true,\"lo" +
            "cation\":\"path\"}},\"parameterOrder\":[\"tasklist\"],\"scopes\":[\"https://www.googleapis" +
            ".com/auth/tasks\"]},\"delete\":{\"id\":\"tasks.tasks.delete\",\"path\":\"lists/{tasklist}/" +
            "tasks/{task}\",\"httpMethod\":\"DELETE\",\"description\":\"Deletes the specified task fr" +
            "om the task list.\",\"parameters\":{\"task\":{\"type\":\"string\",\"description\":\"Task ide" +
            "ntifier.\",\"required\":true,\"location\":\"path\"},\"tasklist\":{\"type\":\"string\",\"descri" +
            "ption\":\"Task list identifier.\",\"required\":true,\"location\":\"path\"}},\"parameterOrd" +
            "er\":[\"tasklist\",\"task\"],\"scopes\":[\"https://www.googleapis.com/auth/tasks\"]},\"get" +
            "\":{\"id\":\"tasks.tasks.get\",\"path\":\"lists/{tasklist}/tasks/{task}\",\"httpMethod\":\"G" +
            "ET\",\"description\":\"Returns the specified task.\",\"parameters\":{\"task\":{\"type\":\"st" +
            "ring\",\"description\":\"Task identifier.\",\"required\":true,\"location\":\"path\"},\"taskl" +
            "ist\":{\"type\":\"string\",\"description\":\"Task list identifier.\",\"required\":true,\"loc" +
            "ation\":\"path\"}},\"parameterOrder\":[\"tasklist\",\"task\"],\"response\":{\"$ref\":\"Task\"}," +
            "\"scopes\":[\"https://www.googleapis.com/auth/tasks\",\"https://www.googleapis.com/au" +
            "th/tasks.readonly\"]},\"insert\":{\"id\":\"tasks.tasks.insert\",\"path\":\"lists/{tasklist" +
            "}/tasks\",\"httpMethod\":\"POST\",\"description\":\"Creates a new task on the specified " +
            "task list.\",\"parameters\":{\"parent\":{\"type\":\"string\",\"description\":\"Parent task i" +
            "dentifier. If the task is created at the top level, this parameter is omitted. O" +
            "ptional.\",\"location\":\"query\"},\"previous\":{\"type\":\"string\",\"description\":\"Previou" +
            "s sibling task identifier. If the task is created at the first position among it" +
            "s siblings, this parameter is omitted. Optional.\",\"location\":\"query\"},\"tasklist\"" +
            ":{\"type\":\"string\",\"description\":\"Task list identifier.\",\"required\":true,\"locatio" +
            "n\":\"path\"}},\"parameterOrder\":[\"tasklist\"],\"request\":{\"$ref\":\"Task\"},\"response\":{" +
            "\"$ref\":\"Task\"},\"scopes\":[\"https://www.googleapis.com/auth/tasks\"]},\"list\":{\"id\":" +
            "\"tasks.tasks.list\",\"path\":\"lists/{tasklist}/tasks\",\"httpMethod\":\"GET\",\"descripti" +
            "on\":\"Returns all tasks in the specified task list.\",\"parameters\":{\"completedMax\"" +
            ":{\"type\":\"string\",\"description\":\"Upper bound for a task\'s completion date (as a " +
            "RFC 3339 timestamp) to filter by. Optional. The default is not to filter by comp" +
            "letion date.\",\"location\":\"query\"},\"completedMin\":{\"type\":\"string\",\"description\":" +
            "\"Lower bound for a task\'s completion date (as a RFC 3339 timestamp) to filter by" +
            ". Optional. The default is not to filter by completion date.\",\"location\":\"query\"" +
            "},\"dueMax\":{\"type\":\"string\",\"description\":\"Upper bound for a task\'s due date (as" +
            " a RFC 3339 timestamp) to filter by. Optional. The default is not to filter by d" +
            "ue date.\",\"location\":\"query\"},\"dueMin\":{\"type\":\"string\",\"description\":\"Lower bou" +
            "nd for a task\'s due date (as a RFC 3339 timestamp) to filter by. Optional. The d" +
            "efault is not to filter by due date.\",\"location\":\"query\"},\"maxResults\":{\"type\":\"" +
            "string\",\"description\":\"Maximum number of task lists returned on one page. Option" +
            "al. The default is 100.\",\"format\":\"int64\",\"location\":\"query\"},\"pageToken\":{\"type" +
            "\":\"string\",\"description\":\"Token specifying the result page to return. Optional.\"" +
            ",\"location\":\"query\"},\"showCompleted\":{\"type\":\"boolean\",\"description\":\"Flag indic" +
            "ating whether completed tasks are returned in the result. Optional. The default " +
            "is True.\",\"location\":\"query\"},\"showDeleted\":{\"type\":\"boolean\",\"description\":\"Fla" +
            "g indicating whether deleted tasks are returned in the result. Optional. The def" +
            "ault is False.\",\"location\":\"query\"},\"showHidden\":{\"type\":\"boolean\",\"description\"" +
            ":\"Flag indicating whether hidden tasks are returned in the result. Optional. The" +
            " default is False.\",\"location\":\"query\"},\"tasklist\":{\"type\":\"string\",\"description" +
            "\":\"Task list identifier.\",\"required\":true,\"location\":\"path\"},\"updatedMin\":{\"type" +
            "\":\"string\",\"description\":\"Lower bound for a task\'s last modification time (as a " +
            "RFC 3339 timestamp) to filter by. Optional. The default is not to filter by last" +
            " modification time.\",\"location\":\"query\"}},\"parameterOrder\":[\"tasklist\"],\"respons" +
            "e\":{\"$ref\":\"Tasks\"},\"scopes\":[\"https://www.googleapis.com/auth/tasks\",\"https://w" +
            "ww.googleapis.com/auth/tasks.readonly\"]},\"move\":{\"id\":\"tasks.tasks.move\",\"path\":" +
            "\"lists/{tasklist}/tasks/{task}/move\",\"httpMethod\":\"POST\",\"description\":\"Moves th" +
            "e specified task to another position in the task list. This can include putting " +
            "it as a child task under a new parent and/or move it to a different position amo" +
            "ng its sibling tasks.\",\"parameters\":{\"parent\":{\"type\":\"string\",\"description\":\"Ne" +
            "w parent task identifier. If the task is moved to the top level, this parameter " +
            "is omitted. Optional.\",\"location\":\"query\"},\"previous\":{\"type\":\"string\",\"descript" +
            "ion\":\"New previous sibling task identifier. If the task is moved to the first po" +
            "sition among its siblings, this parameter is omitted. Optional.\",\"location\":\"que" +
            "ry\"},\"task\":{\"type\":\"string\",\"description\":\"Task identifier.\",\"required\":true,\"l" +
            "ocation\":\"path\"},\"tasklist\":{\"type\":\"string\",\"description\":\"Task list identifier" +
            ".\",\"required\":true,\"location\":\"path\"}},\"parameterOrder\":[\"tasklist\",\"task\"],\"res" +
            "ponse\":{\"$ref\":\"Task\"},\"scopes\":[\"https://www.googleapis.com/auth/tasks\"]},\"patc" +
            "h\":{\"id\":\"tasks.tasks.patch\",\"path\":\"lists/{tasklist}/tasks/{task}\",\"httpMethod\"" +
            ":\"PATCH\",\"description\":\"Updates the specified task. This method supports patch s" +
            "emantics.\",\"parameters\":{\"task\":{\"type\":\"string\",\"description\":\"Task identifier." +
            "\",\"required\":true,\"location\":\"path\"},\"tasklist\":{\"type\":\"string\",\"description\":\"" +
            "Task list identifier.\",\"required\":true,\"location\":\"path\"}},\"parameterOrder\":[\"ta" +
            "sklist\",\"task\"],\"request\":{\"$ref\":\"Task\"},\"response\":{\"$ref\":\"Task\"},\"scopes\":[\"" +
            "https://www.googleapis.com/auth/tasks\"]},\"update\":{\"id\":\"tasks.tasks.update\",\"pa" +
            "th\":\"lists/{tasklist}/tasks/{task}\",\"httpMethod\":\"PUT\",\"description\":\"Updates th" +
            "e specified task.\",\"parameters\":{\"task\":{\"type\":\"string\",\"description\":\"Task ide" +
            "ntifier.\",\"required\":true,\"location\":\"path\"},\"tasklist\":{\"type\":\"string\",\"descri" +
            "ption\":\"Task list identifier.\",\"required\":true,\"location\":\"path\"}},\"parameterOrd" +
            "er\":[\"tasklist\",\"task\"],\"request\":{\"$ref\":\"Task\"},\"response\":{\"$ref\":\"Task\"},\"sc" +
            "opes\":[\"https://www.googleapis.com/auth/tasks\"]}}}}}";
        
        private const string Version = "v1";
        
        private const string Name = "tasks";
        
        private const string BaseUri = "https://www.googleapis.com/tasks/v1/";
        
        private const Google.Apis.Discovery.DiscoveryVersion DiscoveryVersionUsed = Google.Apis.Discovery.DiscoveryVersion.Version_1_0;
        
        private string key;
        
        protected TasksService(Google.Apis.Discovery.IService genericService, Google.Apis.Authentication.IAuthenticator authenticator) {
            this.genericService = genericService;
            this.authenticator = authenticator;
            this.tasklists = new TasklistsResource(this);
            this.tasks = new TasksResource(this);
        }
        
        public TasksService() : 
                this(Google.Apis.Authentication.NullAuthenticator.Instance) {
        }
        
        public TasksService(Google.Apis.Authentication.IAuthenticator authenticator) : 
                this(new Google.Apis.Discovery.DiscoveryService(new Google.Apis.Discovery.StringDiscoveryDevice(DiscoveryDocument)).GetService(TasksService.DiscoveryVersionUsed, new Google.Apis.Discovery.FactoryParameterV1_0(new System.Uri(TasksService.BaseUri))), authenticator) {
        }
        
        /// <summary>Sets the API-Key (or DeveloperKey) which this service uses for all requests</summary>
        public virtual string Key {
            get {
                return this.key;
            }
            set {
                this.key = value;
            }
        }
        
        public virtual Google.Apis.Requests.IRequest CreateRequest(string resource, string method) {
            Google.Apis.Requests.IRequest request = this.genericService.CreateRequest(resource, method);
            if (!string.IsNullOrEmpty(Key)) {
                request = request.WithKey(this.Key);
            }
            return request.WithAuthentication(authenticator);
        }
        
        public virtual void RegisterSerializer(Google.Apis.ISerializer serializer) {
            genericService.Serializer = serializer;
        }
        
        public virtual string SerializeObject(object obj) {
            return genericService.SerializeRequest(obj);
        }
        
        public virtual T DeserializeResponse<T>(Google.Apis.Requests.IResponse response)
         {
            return genericService.DeserializeResponse<T>(response);
        }
        
        /// <summary>A list of all OAuth2.0 scopes. Each of these scopes relates to a permission or group of permissions that different methods of this API may need.</summary>
        public enum Scopes {
            
            /// <summary>Manage your tasks</summary>
            [Google.Apis.Util.StringValueAttribute("https://www.googleapis.com/auth/tasks")]
            Tasks,
            
            /// <summary>View your tasks</summary>
            [Google.Apis.Util.StringValueAttribute("https://www.googleapis.com/auth/tasks.readonly")]
            TasksReadonly,
        }
    }
    
    public class TasklistsResource {
        
        private Google.Apis.Discovery.IRequestProvider service;
        
        private const string Resource = "tasklists";
        
        public TasklistsResource(TasksService service) {
            this.service = service;
        }
        
        /// <summary>Deletes the authenticated user&apos;s specified task list.</summary>
        /// <param name="tasklist">Required - Task list identifier.</param>
        public virtual DeleteRequest Delete(string tasklist) {
            return new DeleteRequest(service, tasklist);
        }
        
        /// <summary>Returns the authenticated user&apos;s specified task list.</summary>
        /// <param name="tasklist">Required - Task list identifier.</param>
        public virtual GetRequest Get(string tasklist) {
            return new GetRequest(service, tasklist);
        }
        
        /// <summary>Creates a new task list and adds it to the authenticated user&apos;s task lists.</summary>
        public virtual InsertRequest Insert(Google.Apis.Tasks.v1.Data.TaskList body) {
            return new InsertRequest(service, body);
        }
        
        /// <summary>Returns all the authenticated user&apos;s task lists.</summary>
        public virtual ListRequest List() {
            return new ListRequest(service);
        }
        
        /// <summary>Updates the authenticated user&apos;s specified task list. This method supports patch semantics.</summary>
        /// <param name="tasklist">Required - Task list identifier.</param>
        public virtual PatchRequest Patch(Google.Apis.Tasks.v1.Data.TaskList body, string tasklist) {
            return new PatchRequest(service, body, tasklist);
        }
        
        /// <summary>Updates the authenticated user&apos;s specified task list.</summary>
        /// <param name="tasklist">Required - Task list identifier.</param>
        public virtual UpdateRequest Update(Google.Apis.Tasks.v1.Data.TaskList body, string tasklist) {
            return new UpdateRequest(service, body, tasklist);
        }
        
        public class DeleteRequest : Google.Apis.Requests.ServiceRequest<string> {
            
            private string tasklist;
            
            public DeleteRequest(Google.Apis.Discovery.IRequestProvider service, string tasklist) : 
                    base(service) {
                this.tasklist = tasklist;
            }
            
            /// <summary>Task list identifier.</summary>
            [Google.Apis.Util.RequestParameterAttribute("tasklist")]
            public virtual string Tasklist {
                get {
                    return this.tasklist;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "tasklists";
                }
            }
            
            protected override string MethodName {
                get {
                    return "delete";
                }
            }
        }
        
        public class GetRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Tasks.v1.Data.TaskList> {
            
            private string tasklist;
            
            public GetRequest(Google.Apis.Discovery.IRequestProvider service, string tasklist) : 
                    base(service) {
                this.tasklist = tasklist;
            }
            
            /// <summary>Task list identifier.</summary>
            [Google.Apis.Util.RequestParameterAttribute("tasklist")]
            public virtual string Tasklist {
                get {
                    return this.tasklist;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "tasklists";
                }
            }
            
            protected override string MethodName {
                get {
                    return "get";
                }
            }
        }
        
        public class InsertRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Tasks.v1.Data.TaskList> {
            
            private Google.Apis.Tasks.v1.Data.TaskList bodyValue;
            
            public InsertRequest(Google.Apis.Discovery.IRequestProvider service, Google.Apis.Tasks.v1.Data.TaskList body) : 
                    base(service) {
                this.Body = body;
            }
            
            /// <summary>Gets/Sets the Body of this Request.</summary>
            public virtual Google.Apis.Tasks.v1.Data.TaskList Body {
                get {
                    return this.bodyValue;
                }
                set {
                    this.bodyValue = value;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "tasklists";
                }
            }
            
            protected override string MethodName {
                get {
                    return "insert";
                }
            }
            
            protected override object GetBody() {
                return this.Body;
            }
        }
        
        public class ListRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Tasks.v1.Data.TaskLists> {
            
            private string maxResults;
            
            private string pageToken;
            
            public ListRequest(Google.Apis.Discovery.IRequestProvider service) : 
                    base(service) {
            }
            
            /// <summary>Maximum number of task lists returned on one page. Optional. The default is 100.</summary>
            [Google.Apis.Util.RequestParameterAttribute("maxResults")]
            public virtual string MaxResults {
                get {
                    return this.maxResults;
                }
                set {
                    this.maxResults = value;
                }
            }
            
            /// <summary>Token specifying the result page to return. Optional.</summary>
            [Google.Apis.Util.RequestParameterAttribute("pageToken")]
            public virtual string PageToken {
                get {
                    return this.pageToken;
                }
                set {
                    this.pageToken = value;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "tasklists";
                }
            }
            
            protected override string MethodName {
                get {
                    return "list";
                }
            }
        }
        
        public class PatchRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Tasks.v1.Data.TaskList> {
            
            private string tasklist;
            
            private Google.Apis.Tasks.v1.Data.TaskList bodyValue;
            
            public PatchRequest(Google.Apis.Discovery.IRequestProvider service, Google.Apis.Tasks.v1.Data.TaskList body, string tasklist) : 
                    base(service) {
                this.Body = body;
                this.tasklist = tasklist;
            }
            
            /// <summary>Task list identifier.</summary>
            [Google.Apis.Util.RequestParameterAttribute("tasklist")]
            public virtual string Tasklist {
                get {
                    return this.tasklist;
                }
            }
            
            /// <summary>Gets/Sets the Body of this Request.</summary>
            public virtual Google.Apis.Tasks.v1.Data.TaskList Body {
                get {
                    return this.bodyValue;
                }
                set {
                    this.bodyValue = value;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "tasklists";
                }
            }
            
            protected override string MethodName {
                get {
                    return "patch";
                }
            }
            
            protected override object GetBody() {
                return this.Body;
            }
        }
        
        public class UpdateRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Tasks.v1.Data.TaskList> {
            
            private string tasklist;
            
            private Google.Apis.Tasks.v1.Data.TaskList bodyValue;
            
            public UpdateRequest(Google.Apis.Discovery.IRequestProvider service, Google.Apis.Tasks.v1.Data.TaskList body, string tasklist) : 
                    base(service) {
                this.Body = body;
                this.tasklist = tasklist;
            }
            
            /// <summary>Task list identifier.</summary>
            [Google.Apis.Util.RequestParameterAttribute("tasklist")]
            public virtual string Tasklist {
                get {
                    return this.tasklist;
                }
            }
            
            /// <summary>Gets/Sets the Body of this Request.</summary>
            public virtual Google.Apis.Tasks.v1.Data.TaskList Body {
                get {
                    return this.bodyValue;
                }
                set {
                    this.bodyValue = value;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "tasklists";
                }
            }
            
            protected override string MethodName {
                get {
                    return "update";
                }
            }
            
            protected override object GetBody() {
                return this.Body;
            }
        }
    }
    
    public class TasksResource {
        
        private Google.Apis.Discovery.IRequestProvider service;
        
        private const string Resource = "tasks";
        
        public TasksResource(TasksService service) {
            this.service = service;
        }
        
        /// <summary>Clears all completed tasks from the specified task list. The affected tasks will be marked as &apos;hidden&apos; and no longer be returned by default when retrieving all tasks for a task list.</summary>
        /// <param name="tasklist">Required - Task list identifier.</param>
        public virtual ClearRequest Clear(string tasklist) {
            return new ClearRequest(service, tasklist);
        }
        
        /// <summary>Deletes the specified task from the task list.</summary>
        /// <param name="tasklist">Required - Task list identifier.</param>
        /// <param name="task">Required - Task identifier.</param>
        public virtual DeleteRequest Delete(string tasklist, string task) {
            return new DeleteRequest(service, tasklist, task);
        }
        
        /// <summary>Returns the specified task.</summary>
        /// <param name="tasklist">Required - Task list identifier.</param>
        /// <param name="task">Required - Task identifier.</param>
        public virtual GetRequest Get(string tasklist, string task) {
            return new GetRequest(service, tasklist, task);
        }
        
        /// <summary>Creates a new task on the specified task list.</summary>
        /// <param name="tasklist">Required - Task list identifier.</param>
        public virtual InsertRequest Insert(Google.Apis.Tasks.v1.Data.Task body, string tasklist) {
            return new InsertRequest(service, body, tasklist);
        }
        
        /// <summary>Returns all tasks in the specified task list.</summary>
        /// <param name="tasklist">Required - Task list identifier.</param>
        public virtual ListRequest List(string tasklist) {
            return new ListRequest(service, tasklist);
        }
        
        /// <summary>Moves the specified task to another position in the task list. This can include putting it as a child task under a new parent and/or move it to a different position among its sibling tasks.</summary>
        /// <param name="tasklist">Required - Task list identifier.</param>
        /// <param name="task">Required - Task identifier.</param>
        public virtual MoveRequest Move(string tasklist, string task) {
            return new MoveRequest(service, tasklist, task);
        }
        
        /// <summary>Updates the specified task. This method supports patch semantics.</summary>
        /// <param name="tasklist">Required - Task list identifier.</param>
        /// <param name="task">Required - Task identifier.</param>
        public virtual PatchRequest Patch(Google.Apis.Tasks.v1.Data.Task body, string tasklist, string task) {
            return new PatchRequest(service, body, tasklist, task);
        }
        
        /// <summary>Updates the specified task.</summary>
        /// <param name="tasklist">Required - Task list identifier.</param>
        /// <param name="task">Required - Task identifier.</param>
        public virtual UpdateRequest Update(Google.Apis.Tasks.v1.Data.Task body, string tasklist, string task) {
            return new UpdateRequest(service, body, tasklist, task);
        }
        
        public class ClearRequest : Google.Apis.Requests.ServiceRequest<string> {
            
            private string tasklist;
            
            public ClearRequest(Google.Apis.Discovery.IRequestProvider service, string tasklist) : 
                    base(service) {
                this.tasklist = tasklist;
            }
            
            /// <summary>Task list identifier.</summary>
            [Google.Apis.Util.RequestParameterAttribute("tasklist")]
            public virtual string Tasklist {
                get {
                    return this.tasklist;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "tasks";
                }
            }
            
            protected override string MethodName {
                get {
                    return "clear";
                }
            }
        }
        
        public class DeleteRequest : Google.Apis.Requests.ServiceRequest<string> {
            
            private string task;
            
            private string tasklist;
            
            public DeleteRequest(Google.Apis.Discovery.IRequestProvider service, string tasklist, string task) : 
                    base(service) {
                this.tasklist = tasklist;
                this.task = task;
            }
            
            /// <summary>Task identifier.</summary>
            [Google.Apis.Util.RequestParameterAttribute("task")]
            public virtual string Task {
                get {
                    return this.task;
                }
            }
            
            /// <summary>Task list identifier.</summary>
            [Google.Apis.Util.RequestParameterAttribute("tasklist")]
            public virtual string Tasklist {
                get {
                    return this.tasklist;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "tasks";
                }
            }
            
            protected override string MethodName {
                get {
                    return "delete";
                }
            }
        }
        
        public class GetRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Tasks.v1.Data.Task> {
            
            private string task;
            
            private string tasklist;
            
            public GetRequest(Google.Apis.Discovery.IRequestProvider service, string tasklist, string task) : 
                    base(service) {
                this.tasklist = tasklist;
                this.task = task;
            }
            
            /// <summary>Task identifier.</summary>
            [Google.Apis.Util.RequestParameterAttribute("task")]
            public virtual string Task {
                get {
                    return this.task;
                }
            }
            
            /// <summary>Task list identifier.</summary>
            [Google.Apis.Util.RequestParameterAttribute("tasklist")]
            public virtual string Tasklist {
                get {
                    return this.tasklist;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "tasks";
                }
            }
            
            protected override string MethodName {
                get {
                    return "get";
                }
            }
        }
        
        public class InsertRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Tasks.v1.Data.Task> {
            
            private string parent;
            
            private string previous;
            
            private string tasklist;
            
            private Google.Apis.Tasks.v1.Data.Task bodyValue;
            
            public InsertRequest(Google.Apis.Discovery.IRequestProvider service, Google.Apis.Tasks.v1.Data.Task body, string tasklist) : 
                    base(service) {
                this.Body = body;
                this.tasklist = tasklist;
            }
            
            /// <summary>Parent task identifier. If the task is created at the top level, this parameter is omitted. Optional.</summary>
            [Google.Apis.Util.RequestParameterAttribute("parent")]
            public virtual string Parent {
                get {
                    return this.parent;
                }
                set {
                    this.parent = value;
                }
            }
            
            /// <summary>Previous sibling task identifier. If the task is created at the first position among its siblings, this parameter is omitted. Optional.</summary>
            [Google.Apis.Util.RequestParameterAttribute("previous")]
            public virtual string Previous {
                get {
                    return this.previous;
                }
                set {
                    this.previous = value;
                }
            }
            
            /// <summary>Task list identifier.</summary>
            [Google.Apis.Util.RequestParameterAttribute("tasklist")]
            public virtual string Tasklist {
                get {
                    return this.tasklist;
                }
            }
            
            /// <summary>Gets/Sets the Body of this Request.</summary>
            public virtual Google.Apis.Tasks.v1.Data.Task Body {
                get {
                    return this.bodyValue;
                }
                set {
                    this.bodyValue = value;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "tasks";
                }
            }
            
            protected override string MethodName {
                get {
                    return "insert";
                }
            }
            
            protected override object GetBody() {
                return this.Body;
            }
        }
        
        public class ListRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Tasks.v1.Data.Tasks> {
            
            private string completedMax;
            
            private string completedMin;
            
            private string dueMax;
            
            private string dueMin;
            
            private string maxResults;
            
            private string pageToken;
            
            private System.Boolean? showCompleted;
            
            private System.Boolean? showDeleted;
            
            private System.Boolean? showHidden;
            
            private string tasklist;
            
            private string updatedMin;
            
            public ListRequest(Google.Apis.Discovery.IRequestProvider service, string tasklist) : 
                    base(service) {
                this.tasklist = tasklist;
            }
            
            /// <summary>Upper bound for a task's completion date (as a RFC 3339 timestamp) to filter by. Optional. The default is not to filter by completion date.</summary>
            [Google.Apis.Util.RequestParameterAttribute("completedMax")]
            public virtual string CompletedMax {
                get {
                    return this.completedMax;
                }
                set {
                    this.completedMax = value;
                }
            }
            
            /// <summary>Lower bound for a task's completion date (as a RFC 3339 timestamp) to filter by. Optional. The default is not to filter by completion date.</summary>
            [Google.Apis.Util.RequestParameterAttribute("completedMin")]
            public virtual string CompletedMin {
                get {
                    return this.completedMin;
                }
                set {
                    this.completedMin = value;
                }
            }
            
            /// <summary>Upper bound for a task's due date (as a RFC 3339 timestamp) to filter by. Optional. The default is not to filter by due date.</summary>
            [Google.Apis.Util.RequestParameterAttribute("dueMax")]
            public virtual string DueMax {
                get {
                    return this.dueMax;
                }
                set {
                    this.dueMax = value;
                }
            }
            
            /// <summary>Lower bound for a task's due date (as a RFC 3339 timestamp) to filter by. Optional. The default is not to filter by due date.</summary>
            [Google.Apis.Util.RequestParameterAttribute("dueMin")]
            public virtual string DueMin {
                get {
                    return this.dueMin;
                }
                set {
                    this.dueMin = value;
                }
            }
            
            /// <summary>Maximum number of task lists returned on one page. Optional. The default is 100.</summary>
            [Google.Apis.Util.RequestParameterAttribute("maxResults")]
            public virtual string MaxResults {
                get {
                    return this.maxResults;
                }
                set {
                    this.maxResults = value;
                }
            }
            
            /// <summary>Token specifying the result page to return. Optional.</summary>
            [Google.Apis.Util.RequestParameterAttribute("pageToken")]
            public virtual string PageToken {
                get {
                    return this.pageToken;
                }
                set {
                    this.pageToken = value;
                }
            }
            
            /// <summary>Flag indicating whether completed tasks are returned in the result. Optional. The default is True.</summary>
            [Google.Apis.Util.RequestParameterAttribute("showCompleted")]
            public virtual System.Boolean? ShowCompleted {
                get {
                    return this.showCompleted;
                }
                set {
                    this.showCompleted = value;
                }
            }
            
            /// <summary>Flag indicating whether deleted tasks are returned in the result. Optional. The default is False.</summary>
            [Google.Apis.Util.RequestParameterAttribute("showDeleted")]
            public virtual System.Boolean? ShowDeleted {
                get {
                    return this.showDeleted;
                }
                set {
                    this.showDeleted = value;
                }
            }
            
            /// <summary>Flag indicating whether hidden tasks are returned in the result. Optional. The default is False.</summary>
            [Google.Apis.Util.RequestParameterAttribute("showHidden")]
            public virtual System.Boolean? ShowHidden {
                get {
                    return this.showHidden;
                }
                set {
                    this.showHidden = value;
                }
            }
            
            /// <summary>Task list identifier.</summary>
            [Google.Apis.Util.RequestParameterAttribute("tasklist")]
            public virtual string Tasklist {
                get {
                    return this.tasklist;
                }
            }
            
            /// <summary>Lower bound for a task's last modification time (as a RFC 3339 timestamp) to filter by. Optional. The default is not to filter by last modification time.</summary>
            [Google.Apis.Util.RequestParameterAttribute("updatedMin")]
            public virtual string UpdatedMin {
                get {
                    return this.updatedMin;
                }
                set {
                    this.updatedMin = value;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "tasks";
                }
            }
            
            protected override string MethodName {
                get {
                    return "list";
                }
            }
        }
        
        public class MoveRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Tasks.v1.Data.Task> {
            
            private string parent;
            
            private string previous;
            
            private string task;
            
            private string tasklist;
            
            public MoveRequest(Google.Apis.Discovery.IRequestProvider service, string tasklist, string task) : 
                    base(service) {
                this.tasklist = tasklist;
                this.task = task;
            }
            
            /// <summary>New parent task identifier. If the task is moved to the top level, this parameter is omitted. Optional.</summary>
            [Google.Apis.Util.RequestParameterAttribute("parent")]
            public virtual string Parent {
                get {
                    return this.parent;
                }
                set {
                    this.parent = value;
                }
            }
            
            /// <summary>New previous sibling task identifier. If the task is moved to the first position among its siblings, this parameter is omitted. Optional.</summary>
            [Google.Apis.Util.RequestParameterAttribute("previous")]
            public virtual string Previous {
                get {
                    return this.previous;
                }
                set {
                    this.previous = value;
                }
            }
            
            /// <summary>Task identifier.</summary>
            [Google.Apis.Util.RequestParameterAttribute("task")]
            public virtual string Task {
                get {
                    return this.task;
                }
            }
            
            /// <summary>Task list identifier.</summary>
            [Google.Apis.Util.RequestParameterAttribute("tasklist")]
            public virtual string Tasklist {
                get {
                    return this.tasklist;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "tasks";
                }
            }
            
            protected override string MethodName {
                get {
                    return "move";
                }
            }
        }
        
        public class PatchRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Tasks.v1.Data.Task> {
            
            private string task;
            
            private string tasklist;
            
            private Google.Apis.Tasks.v1.Data.Task bodyValue;
            
            public PatchRequest(Google.Apis.Discovery.IRequestProvider service, Google.Apis.Tasks.v1.Data.Task body, string tasklist, string task) : 
                    base(service) {
                this.Body = body;
                this.tasklist = tasklist;
                this.task = task;
            }
            
            /// <summary>Task identifier.</summary>
            [Google.Apis.Util.RequestParameterAttribute("task")]
            public virtual string Task {
                get {
                    return this.task;
                }
            }
            
            /// <summary>Task list identifier.</summary>
            [Google.Apis.Util.RequestParameterAttribute("tasklist")]
            public virtual string Tasklist {
                get {
                    return this.tasklist;
                }
            }
            
            /// <summary>Gets/Sets the Body of this Request.</summary>
            public virtual Google.Apis.Tasks.v1.Data.Task Body {
                get {
                    return this.bodyValue;
                }
                set {
                    this.bodyValue = value;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "tasks";
                }
            }
            
            protected override string MethodName {
                get {
                    return "patch";
                }
            }
            
            protected override object GetBody() {
                return this.Body;
            }
        }
        
        public class UpdateRequest : Google.Apis.Requests.ServiceRequest<Google.Apis.Tasks.v1.Data.Task> {
            
            private string task;
            
            private string tasklist;
            
            private Google.Apis.Tasks.v1.Data.Task bodyValue;
            
            public UpdateRequest(Google.Apis.Discovery.IRequestProvider service, Google.Apis.Tasks.v1.Data.Task body, string tasklist, string task) : 
                    base(service) {
                this.Body = body;
                this.tasklist = tasklist;
                this.task = task;
            }
            
            /// <summary>Task identifier.</summary>
            [Google.Apis.Util.RequestParameterAttribute("task")]
            public virtual string Task {
                get {
                    return this.task;
                }
            }
            
            /// <summary>Task list identifier.</summary>
            [Google.Apis.Util.RequestParameterAttribute("tasklist")]
            public virtual string Tasklist {
                get {
                    return this.tasklist;
                }
            }
            
            /// <summary>Gets/Sets the Body of this Request.</summary>
            public virtual Google.Apis.Tasks.v1.Data.Task Body {
                get {
                    return this.bodyValue;
                }
                set {
                    this.bodyValue = value;
                }
            }
            
            protected override string ResourcePath {
                get {
                    return "tasks";
                }
            }
            
            protected override string MethodName {
                get {
                    return "update";
                }
            }
            
            protected override object GetBody() {
                return this.Body;
            }
        }
    }
    
    public partial class TasksService {
        
        private const string Resource = "";
        
        private TasklistsResource tasklists;
        
        private TasksResource tasks;
        
        private Google.Apis.Discovery.IRequestProvider service {
            get {
                return this;
            }
        }
        
        public virtual TasklistsResource Tasklists {
            get {
                return this.tasklists;
            }
        }
        
        public virtual TasksResource Tasks {
            get {
                return this.tasks;
            }
        }
    }
}
